# -*- coding: utf-8 -*-
import re
import os

dict_path = r"e:\Turtle Wow\Interface\AddOns\pfUI\modules\translator_dict.lua"

# Base de datos de traducciones oficiales al chino para los términos contextuales exactos de WoW
zh_db = {
    # Chat / Slang / Respuestas rápidas
    "jk": "开玩笑", "es broma": "开玩笑", "just kidding": "开玩笑",
    "nt": "尽力了", "buen intento": "尽力了", "good attempt": "尽力了",
    "tengo lag": "我卡了", "i have lag": "我卡了",
    "regresé": "我回来了", "estoy de vuelta": "我回来了", "i am back": "我回来了", "im back": "我回来了",
    "vuelvo enseguida": "马上回来", "ya vengo": "马上回来", "brb": "马上回来",
    
    # Combate / Tácticas / Fases e Intentos
    "tercer intento": "第三次尝试", "third attempt": "第三次尝试",
    "fase 1": "第一阶段", "phase 1": "第一阶段",
    "fase 2": "第二阶段", "phase 2": "第二阶段",
    "fase 3": "第三阶段", "phase 3": "第三阶段",
    "fase 4": "第四阶段", "phase 4": "第四阶段",
    "quédense ahí": "待在那", "stay there": "待在那",
    "vengan aquí": "过来", "come here": "过来",
    "vénganse con el tanque": "靠近坦克", "come to the tank": "靠近坦克",
    "síganme": "跟我来", "follow me": "跟我来",
    "pareen": "稍等", "esperen": "稍等", "hold on": "稍等",
    "aguanten": "坚守阵地", "hold your position": "坚守阵地",
    "no entren todavía": "先别进去", "don't go in yet": "先别进去",
    "lista de objetivos": "击杀顺序", "orden de muerte": "击杀顺序", "kill order": "击杀顺序",
    "foco en el calavera": "打骷髅", "focus skull": "打骷髅",
    "maten la calavera": "击杀骷髅", "kill skull": "击杀骷髅",
    "foco en la equis": "打大叉", "focus cross": "打大叉",
    "trampa a la luna": "冰月亮", "trap moon": "冰月亮",
    "oveja al cuadrado": "羊方块", "sheep square": "羊方块",
    "sap al triángulo": "闷三角", "sap triangle": "闷三角",
    "bandage": "绷带", "venda": "绷带",
    "curación de emergencia": "紧急治疗", "emergency heal": "紧急治疗",
    "intervención de guerra": "拦截", "intercept": "拦截",
    "carga": "冲锋", "charge": "冲锋",
    "provocar": "嘲讽", "mockery": "嘲讽", "provokar": "嘲讽", "taunt": "嘲讽",
    "interrumpir": "打断", "interrupt": "打断",
    "interrumpan el casteo": "打断施法", "interrupt the cast": "打断施法",
    "silencio al healer": "沉默治疗", "silence the healer": "沉默治疗",
    "nido de agro": "消仇恨", "aggro dump": "消仇恨",
    "resistió": "抵抗", "resisted": "抵抗",
    "esquivó": "躲闪", "dodged": "躲闪",
    "paró": "招架", "parried": "招架",
    "bloqueó": "格挡", "blocked": "格挡",
    "inmunidad": "免疫", "immune": "免疫",
    "aturdido": "被晕", "stunned": "被晕",
    "dormido": "被闷", "sapped": "被闷",
    "enraizado": "被缠绕", "rooted": "被缠绕",
    "congelado": "被冰冻", "frozen": "被冰冻",
    "encadenado": "被束缚", "shackled": "被束缚",
    "desafiado": "被嘲讽", "taunted": "被嘲讽",
    "maldecido": "被诅咒", "cursed": "被诅咒",
    "envenenado": "中毒", "poisoned": "中毒",
    "enfermedad": "疾病", "disease": "疾病",
    "maldición": "诅咒", "curse": "诅咒",
    "disipar la maldición": "解除诅咒", "remove curse": "解除诅咒",
    "quitar el veneno": "驱散毒素", "cure poison": "驱散毒素",
    "quitar enfermedad": "驱散疾病", "cure disease": "驱散疾病",
    "disipar": "驱散", "dispel": "驱散",
    "limpieza": "清洁", "cleanse": "清洁",
    "limpiarme": "清洁我", "cleanse me": "清洁我",
    "decursar": "解诅咒", "decurse": "解诅咒",
    "corte de batalla": "战斗打断", "battle cut": "战斗打断",
    
    # Marcas
    "calavera": "骷髅", "skull": "骷髅",
    "equis": "大叉", "cross": "大叉",
    "círculo": "大饼", "circle": "大饼",
    "luna": "月亮", "moon": "月亮",
    "triángulo": "三角", "triangle": "三角",
    "diamante": "菱形", "diamond": "菱形",
    "cuadrado": "方块", "square": "方块",
    "estrella": "星星", "star": "星星",
    "pon marcas": "标记", "put markers": "标记",
    "quita las marcas": "清除标记", "remove markers": "清除标记",
    "marca en el objetivo": "标记目标", "mark the target": "标记目标",
    "maten al marcado": "击杀标记", "kill the marked": "击杀标记",
    "foco en la marca": "打标记", "focus the marker": "打标记",
    
    # Economía y Botín
    "vendo": "出售", "wts": "出售",
    "compro": "求购", "wtb": "求购",
    "cambio": "交换", "wtt": "交换",
    "se liga al equipar": "装备后绑定", "bind on equip": "装备后绑定", "boe": "装绑",
    "se liga al recoger": "拾取后绑定", "bind on pickup": "拾取后绑定", "bop": "拾绑",
    "puja mínima": "最低出价", "minimum bid": "最低出价",
    "oferta inicial": "起拍价", "opening bid": "起拍价",
    "a la una": "一次", "going once": "一次",
    "a las dos": "两次", "going twice": "两次",
    "vendido": "成交", "sold": "成交",
    "todo looteado": "全部拾取", "all looted": "全部拾取",
    "reparto de oro": "分金", "gold payout": "分金",
    "mi parte del gdkp": "我的G分红", "my gdkp cut": "我的G分红",
    "gdkp": "金团", "gold dkp run": "金团",
    "dkp": "DKP", "dragon kill points": "DKP",
    "modo de saqueo": "分配模式", "loot mode": "分配模式",
    "maestro despojador": "队长分配", "master looter": "队长分配",
    "libre para todos": "自由拾取", "free for all": "自由拾取",
    "distribucion grupal": "队伍分配", "group loot": "队伍分配",
    "turno rotativo": "轮流拾取", "round robin": "轮流拾取",
    "reserva suave": "软保留", "soft reserve": "软保留",
    "reserva dura": "硬保留", "hard reserve": "硬保留",
    "rama principal": "主天赋", "main spec": "主天赋",
    "rama secundaria": "副天赋", "off spec": "副天赋",
    "ms os": "主副天赋", "main spec off spec": "主副天赋",
    "solo ms": "仅限主天赋", "main spec only": "仅限主天赋",
    "tira dados": "R点", "roll for it": "R点",
    "tira un dado": "R点", "roll": "R点",
    "necesidad o codicia": "需求 o 贪婪", "need or greed": "需求或贪婪",
    "pasa el loot": "放弃", "pass on loot": "放弃",
    "desencantar": "分解", "disenchant": "分解",
    "desencanta": "分解它", "de it": "分解它",
    "desen": "分解", "de": "分解",
    "barato": "便宜", "cheap": "便宜",
    "caro": "贵", "expensive": "贵",
    "precio de oferta": "一口价", "buyout price": "一口价",
    "precio de subasta": "竞拍价", "auction price": "竞拍价",
    "en subasta": "在拍卖行", "on ah": "在拍卖行",
    "casa de subastas": "拍卖行", "auction house": "拍卖行",
    "subasta": "拍卖行", "ah": "拍卖行",
    "buzón": "邮箱", "mailbox": "邮箱",
    "correo en el juego": "游戏邮件", "in-game mail": "游戏邮件",
    "banco de hermandad": "公会银行", "guild bank": "公会银行",
    "más barato que la subasta": "比拍卖行便宜", "cheaper than ah": "比拍卖行便宜",
    "pagado": "已付", "paid out": "已付",
    "cobrado": "已收", "charged": "已收",
    "gratis": "免费", "free": "免费",
    "sin cargo": "免费", "no charge": "免费",
    "donacion": "捐赠", "donation": "捐赠",
    "propina": "小费", "tip": "小费",
    "propina incluida": "含小费", "tip included": "含小费",
    "acepto propinas": "接受小费", "tips accepted": "接受小费",
    
    # Clases / Roles / Specs
    "daño": "伤害", "damage": "伤害",
    "protección": "防护", "protection": "防护",
    "proteccion": "防护",
    "sagrado": "神圣", "holy": "神圣",
    "represalia": "惩戒", "retribution": "惩戒",
    "sombras": "暗影", "shadow": "暗影",
    "disciplina": "戒律", "discipline": "戒律",
    "restauración": "恢复", "restoration": "恢复",
    "restauracion": "恢复",
    "elemental": "元素", "elemental": "元素",
    "mejora": "增强", "enhancement": "增强",
    "aflicción": "痛苦", "affliction": "痛苦",
    "afliccion": "痛苦",
    "destrucción": "毁灭", "destruction": "毁灭",
    "destruccion": "毁灭",
    "demonología": "恶魔学识", "demonology": "恶魔学识",
    "demonologia": "恶魔学识",
    "escarcha": "冰霜", "frost": "冰霜",
    "fuego": "火焰", "fire": "火焰",
    "arcane": "奥术", "arcano": "奥术",
    "equilibrio": "平衡", "balance": "平衡",
    "feral": "野性", "feral": "野性",
    "combate": "战斗", "combat": "战斗",
    "asesino": "刺杀", "assassination": "刺杀",
    "puntería": "射击", "marksmanship": "射击",
    "punteria": "射击",
    "bestias": "野兽控制", "beast mastery": "野兽控制",
    "supervivencia": "生存", "survival": "生存",
    "arms": "武器", "armas": "武器",
    "fury": "狂怒", "furia guerrera": "狂怒",
    "dual spec": "双天赋", "doble especialización": "双天赋", "doble especializacion": "双天赋", "doble spec": "双天赋",

    # Habilidades Guerrero
    "heroic strike": "英勇打击", "golpe heroico": "英勇打击",
    "whirlwind": "旋风斩", "espiral de tormenta": "旋风斩", "remolino": "旋风斩",
    "execute": "斩杀", "ejecutar": "斩杀",
    "sunder armor": "破甲", "hendir armadura": "破甲",
    "battle shout": "战斗怒吼", "grito de batalla": "战斗怒吼",
    "shield wall": "盾墙", "muro de escudo": "盾墙",
    "retaliation": "反击风暴", "represalia de guerra": "反击风暴", "represalia": "反击风暴",
    "last stand": "破釜沉舟", "último aliento": "破釜沉舟",
    "mortal strike": "致死打击", "golpe mortal": "致死打击",
    "charge": "冲锋", "embestida": "冲锋",
    "berserker charge": "拦截", "carga de berserker": "拦截",
    "intercept": "拦截", "interceptar": "拦截",
    "shield bash": "盾击", "golpe de escudo": "盾击",
    "devastate": "毁灭打击", "aplastar": "毁灭打击",
    "demoralizing shout": "挫志怒吼", "intimidar": "挫志怒吼",
    "intimidating shout": "破胆怒吼", "grito de batalla": "破胆怒吼", "grito aterrador": "破胆怒吼",

    # Habilidades Paladín
    "flash of light": "圣光闪现", "destello de luz": "圣光闪现",
    "holy light": "圣光术", "luz sagrada": "圣光术",
    "judgement": "审判", "sentencia": "审判",
    "divine shield": "圣盾术", "escudo divino": "圣盾术", "burbuja": "圣盾术",
    "lay on hands": "圣疗术", "imposición de manos": "圣疗术",
    "seal of justice": "公正圣印", "sello de justicia": "公正圣印",
    "seal of wisdom": "智慧圣印", "sello de sabiduría": "智慧圣印",
    "seal of the crusader": "十字军圣印", "sello de la cruzada": "十字军圣印",
    "seal of righteousness": "正义圣印", "sello de virtud": "正义圣印",
    "seal of command": "命令圣印", "sello de mando": "命令圣印",
    "divine favor": "神恩术", "pureza divina": "神恩术",
    "consecration": "奉献", "consagración": "奉献",
    "blessing of kings": "王者祝福", "bendición de reyes": "王者祝福",
    "blessing of wisdom": "智慧祝福", "bendición de sabiduría": "智慧祝福",
    "blessing of might": "力量祝福", "bendición de poder": "力量祝福",
    "blessing of salvation": "拯救祝福", "bendición de salvación": "拯救祝福",
    "blessing of protection": "保护祝福", "bendición de protección": "保护祝福",
    "devotion aura": "虔诚光环", "aura de devoción": "虔诚光环",
    "retribution aura": "惩罚光环", "aura de retribución": "惩罚光环",
    "concentration aura": "专注光环", "aura de concentración": "专注光环",
    "fire resistance aura": "抗火光环", "aura resistencia fuego": "抗火光环",
    "cleanse": "清洁术", "purificar": "清洁术",
    "holy wrath": "神圣愤怒", "ira sacrada": "神圣愤怒",
    "hammer of justice": "制裁之锤", "martillo del inquisidor": "制裁之锤",
    "hammer of wrath": "愤怒之锤", "escudo de cero": "愤怒之锤",

    # Habilidades Cazador
    "aimed shot": "瞄准射击", "disparo de puntería": "瞄准射击",
    "multi-shot": "多重射击", "multidisparo": "多重射击",
    "feign death": "假死", "fingir muerte": "假死",
    "hunter's mark": "猎人印记", "marca del cazador": "猎人印记",
    "aspect of the hawk": "雄鹰守护", "aspect of the halcón": "雄鹰守护",
    "aspect of the monkey": "灵猴守护", "aspect del mono": "灵猴守护",
    "aspect of the wild": "野性守护", "aspect de bestia salvaje": "野性守护",
    "aspect of the cheetah": "猎豹守护", "aspect del chacal": "猎豹守护",
    "immolation trap": "献祭陷阱", "trampa de fuego": "献祭陷阱",
    "frost trap": "冰霜陷阱", "trampa de hielo": "冰霜陷阱",
    "snake trap": "毒蛇陷阱", "trampa de serpiente": "毒蛇陷阱",
    "explosive trap": "爆炸陷阱", "trampa explosiva": "爆炸陷阱",
    "freezing trap": "冰冻陷阱", "trampa de hielo glacial": "冰冻陷阱",
    "serpent sting": "毒蛇钉刺", "disparo de serpiente": "毒蛇钉刺",
    "scorpid sting": "蝎毒钉刺", "disparo de escorpión": "蝎毒钉刺",
    "viper sting": "蝮蛇钉刺", "disparo de víbora": "蝮蛇钉刺",
    "call pet": "召唤宠物", "invocar mascota": "召唤宠物",
    "dismiss pet": "解散宠物", "liberar mascota": "解散宠物",
    "feed pet": "喂养宠物", "alimentar mascota": "喂养宠物",
    "beast within": "狂野怒火", "duelo de bestias": "狂野怒火",
    "eyes of the beast": "野兽之眼", "ojos de bestia": "野兽之眼",

    # Habilidades Pícaro
    "sap": "闷棍", "porrazo": "闷棍",
    "cheap shot": "偷袭", "golpe bajo": "偷袭",
    "kidney shot": "肾击", "golpe en los riñones": "肾击",
    "evasion": "闪避", "evasión": "闪避",
    "vanish": "消失", "esfumarse": "消失",
    "blind": "致盲", "ceguera": "致盲",
    "deadly poison": "致命毒药", "veneno mortal": "致命毒药",
    "instant poison": "速效毒药", "veneno instantáneo": "速效毒药",
    "hemorrhage": "出血", "hemorragia": "出血",
    "backstab": "背刺", "puñalada": "背刺",
    "sinister strike": "影袭", "golpe sinérgico": "影袭",
    "rupture": "割裂", "ruptura": "割裂",
    "slice and dice": "切割", "rebanada y dados": "切割",
    "expose armor": "破甲", "exposición de armadura": "破甲",
    "fan of knives": "刀扇", "abanico de cuchillos": "刀扇",
    "blade flurry": "剑刃乱舞", "trampa de cuchillas": "剑刃乱舞",
    "cold blood": "冷血", "danza de la muerte": "冷血",
    "stealth": "潜行", "sigilo": "潜行",
    "ambush": "伏击", "emboscada": "伏击",
    "mutilate": "毁伤", "mutilación": "毁伤",
    "eviscerate": "剔骨", "eviscerar": "剔骨",

    # Habilidades Sacerdote
    "greater heal": "强效治疗术", "sanación superior": "强效治疗术", "ánimo mayor": "强效治疗术",
    "flash heal": "快速治疗", "sanación relámpago": "快速治疗",
    "power word: shield": "真言术：盾", "escudo de poder": "真言术：盾", "burbuja del sacerdote": "真言术：盾",
    "power infusion": "能量灌注", "infusión de poder": "能量灌注",
    "shadow word: death": "暗言术：灭", "palabra oscura muerte": "暗言术：灭",
    "shadow word: pain": "暗言术：痛", "palabra oscura dolor": "暗言术：痛",
    "mind flay": "精神鞭笞", "mente del vuelo": "精神鞭笞",
    "mind blast": "心灵震爆", "mente en explosión": "心灵震爆",
    "renew": "恢复", "regeneración": "恢复",
    "heal": "治疗术", "toque de curación": "治疗术",
    "circle of healing": "治疗环", "curación circular": "治疗环",
    "divine spirit": "神圣之灵", "renacer del sacerdote": "神圣之灵", "espíritu divino": "神圣之灵",
    "prayer of fortitude": "坚韧祷言", "oración de fortalecimiento": "坚韧祷言",
    "prayer of shadow protection": "暗影防护祷言", "oración de sombra": "暗影防护祷言",
    "vampiric embrace": "吸血鬼的拥抱", "fortaleza de las sombras": "吸血鬼的拥抱", "abrazo vampírico": "吸血鬼的拥抱",
    "vampiric touch": "吸血鬼之触", "toque vampírico": "吸血鬼之触",
    "shadowform": "暗影形态", "forma de sombra": "暗影形态",
    "fade": "渐隐术", "desvanecer": "渐隐术",
    "dispel magic": "驱散魔法", "dispersar": "驱散魔法",
    "mass dispel": "群体驱散", "limpieza masiva": "群体驱散",
    "divine compassion": "神圣慈悲", "compasión divina": "神圣慈悲",

    # Habilidades Mago
    "frostbolt": "寒冰箭", "descarga de escarcha": "寒冰箭",
    "fireball": "火球术", "bola de fuego": "火球术",
    "ice block": "寒冰屏障", "bloque de hielo": "寒冰屏障",
    "polymorph": "变形术", "polimorfia": "变形术", "oveja": "变形术",
    "blink": "闪现术", "traslación": "闪现术",
    "cone of cold": "冰锥术", "cono de frío": "冰锥术",
    "frost nova": "冰霜新星", "joya de escarcha": "冰霜新星",
    "arcane missiles": "奥术飞弹", "proyectil arcano": "奥术飞弹",
    "arcane explosion": "奥术爆炸", "explosión arcana": "奥术爆炸",
    "counterspell": "法术反制", "contrahechizo": "法术反制",
    "combustion": "燃烧", "combustión": "燃烧",
    "presence of mind": "气定神闲", "presencia mental": "气定神闲",
    "blizzard": "暴风雪", "ventisca": "暴风雪",
    "flamestrike": "烈焰风暴", "tormenta de fuego": "烈焰风暴",
    "fire blast": "火焰冲击", "explosión de fuego": "火焰冲击",
    "mirror image": "镜像", "espejo de imágenes": "镜像",
    "conjure table": "拉桌子", "mesa de banquete": "拉桌子",
    "conjure water": "造水术", "conjurar agua": "造水术",
    "conjure food": "造食术", "conjurar comida": "造食术",
    "portal: stormwind": "传送门：暴风城", "portal a ventormenta": "传送门：暴风城",
    "portal: orgrimmar": "传送门：奥格瑞玛", "portal a orgrimmar": "传送门：奥格瑞玛",
    "portal: ironforge": "传送门：铁炉堡", "portal a ironforge": "传送门：铁炉堡",
    "portal: darnassus": "传送门：达纳苏斯", "portal a darnassus": "传送门：达纳苏斯",
    "portal: undercity": "传送门：幽暗城", "portal a entrañas": "传送门：幽暗城",
    "portal: thunder bluff": "传送门：雷霆崖", "portal a thunder bluff": "传送门：雷霆崖",
    "teleport: stormwind": "传送：暴风城", "tele ventormenta": "传送：暴风城",
    "teleport: orgrimmar": "传送：奥格瑞玛", "tele orgrimmar": "传送：奥格瑞玛",
    "shatter": "碎冰", "romper nieve": "碎冰",

    # Habilidades Brujo
    "shadow bolt": "暗影箭", "descarga de sombras": "暗影箭",
    "corruption": "腐蚀术", "corrupción": "腐蚀术",
    "curse of agony": "痛苦诅咒", "maldición de agonía": "痛苦诅咒",
    "curse of the elements": "元素诅咒", "maldición de elementos": "元素诅咒",
    "curse of weakness": "虚弱诅咒", "maldición de debilidad": "虚弱诅咒",
    "curse of exhaustion": "疲劳诅咒", "maldición de agotamiento": "疲劳诅咒",
    "rain of fire": "火雨", "lluvia de fuego": "火雨",
    "hellfire": "地狱烈焰", "tempestad infernal": "地狱烈焰",
    "drain life": "吸取生命", "drenar vida": "吸取生命",
    "drain soul": "吸取灵魂", "drenar alma": "吸取灵魂",
    "drain mana": "吸取法力", "drenar maná": "吸取法力",
    "banish": "放逐术", "destierro": "放逐术",
    "seduction": "诱惑", "seducción": "诱惑",
    "enslave demon": "奴役恶魔", "atar demonio": "奴役恶魔",
    "sacrifice": "牺牲", "sacrificio maléfico": "牺牲",
    "conflagrate": "燃烧", "lengua de fuego": "燃烧",
    "fire bolt": "火焰箭", "tiro de fuego": "火焰箭",
    "create healthstone": "制造治疗石", "creación ropas de tela": "制造治疗石",
    "healthstone": "制造治疗石", "piedra de salud": "治疗石",
    "soulstone": "灵魂石", "piedra de alma": "灵魂石",
    "soulstone rez": "灵魂石复活", "resurrección del brujo": "灵魂石复活",
    "soulstone me": "给我绑定灵魂石", "soulstone a mi": "给我绑定灵魂石", "ponme soulstone": "给我绑定灵魂石",

    # Habilidades Chamán
    "lightning bolt": "闪电箭", "descarga de relámpagos": "闪电箭",
    "chain lightning": "闪电链", "cadena de relámpagos": "闪电链",
    "bloodlust": "嗜血", "ansia de sangre": "嗜血",
    "heroism": "英雄", "heroísmo": "英雄",
    "windfury": "风怒", "furia del viento": "风怒",
    "lightning shield": "闪电盾", "escudo del relámpago": "闪电盾",
    "water shield": "水之护盾", "escudo del agua": "水之护盾",
    "chain heal": "治疗链", "curación de cadena": "治疗链",
    "healing wave": "治疗波", "marea de oleadas": "治疗波",
    "lesser healing wave": "次级治疗波", "oleada menor": "次级治疗波",
    "earth shock": "大地震击", "golpe de tierra": "大地震击",
    "frost shock": "冰霜震击", "golpe de escarcha": "冰霜震击",
    "flame shock": "烈焰震击", "golpe de llama": "烈焰震击",
    "wind shear": "风剪", "ráfaga de viento": "风剪",
    "earthbind totem": "地缚图腾", "tótem de terratemblor": "地缚图腾",
    "searing totem": "灼热图腾", "tótem de llama chispa": "灼热图腾",
    "magma totem": "熔岩图腾", "tótem de magma": "熔岩图腾",
    "healing stream totem": "治疗之泉图腾", "tótem de curación": "治疗之泉图腾",
    "mana spring totem": "法力之泉图腾", "tótem de maná primavera": "法力之泉图腾",
    "grace of air totem": "风之优雅图腾", "tótem de gracia del aire": "风之优雅图腾",
    "strength of earth totem": "大地之力图腾", "tótem de fuerza de tierra": "大地之力图腾",
    "fire resistance totem": "抗火图腾", "tótem de resistencia fuego": "抗火图腾",
    "nature resistance totem": "抗自然图腾", "tótem de resistencia naturaleza": "抗自然图腾",
    "tremor totem": "战栗图腾", "tótem de sentido de la tierra": "战栗图腾",
    "stoneclaw totem": "石爪图腾", "tótem de intuición": "石爪图腾",
    "drop totem": "插图腾", "invocar tótem": "插图腾",
    "kill the totems": "打图腾", "revienta los totems": "打图腾",

    # Habilidades Druida
    "healing touch": "治疗之触", "toque de sanación": "治疗之触",
    "innervate": "激活", "estimular": "激活",
    "rebirth": "复生", "renacer": "复生",
    "battle rez": "战复", "battle res": "战复", "resurrección de combate": "战复",
    "rejuvenation": "回春术", "rejuvenecimiento": "回春术",
    "lifebloom": "生命绽放", "floración": "生命绽放",
    "regrowth": "愈合", "alimentación regenerativa": "愈合",
    "bear form": "熊形态", "forma de oso": "熊形态",
    "travel form": "旅行形态", "forma de viaje": "旅行形态",
    "tree form": "生命之树形态", "forma de arbol": "生命之树形态",
    "aquatic form": "水栖形态", "forma acuática": "水栖形态",
    "cat form": "猎豹形态", "forma de gato": "猎豹形态",
    "flight form": "飞行形态", "forma de vuelo": "飞行形态",
    "cyclone": "旋风", "ciclón": "旋风",
    "entangling roots": "纠缠根须", "enredar": "纠缠根须",
    "hibernate": "休眠", "dormir a la bestia": "休眠", "hibernar a la bestia": "休眠",
    "nature's grasp": "自然之握", "zarpa de la naturaleza": "自然之握",
    "ravage": "毁灭", "apuñalar": "毁灭",
    "rake": "斜掠", "golpe de raptor": "斜掠",
    "maul": "重击",
    "demoralizing roar": "挫志咆哮", "rugido del oso": "挫志咆哮",
    "war stomp": "战争践踏", "rugido de guerra": "战争践踏",
    "moonfire": "月火术", "luna estelar": "月火术",
    "starfall": "星辰坠落", "lluvia estelar": "星辰坠落",
    "wrath": "愤怒", "ira de naturaleza": "愤怒",
    "solar beam": "日光术", "tormenta solar": "日光术",

    # Atributos / Stats
    "strength": "力量", "fuerza": "力量", "str": "力量",
    "agility": "敏捷", "agilidad": "敏捷", "agi": "敏捷",
    "intellect": "智力", "intelecto": "智力", "int": "智力",
    "spirit": "精神", "espíritu": "精神", "spi": "精神",
    "stamina": "耐力", "aguante": "耐力", "sta": "耐力",
    "attack power": "攻击强度", "poder de ataque": "攻击强度",
    "spell power": "法术强度", "poder con hechizos": "法术强度", "poder de hechizos": "法术强度",
    "spell damage": "法术伤害", "daño con hechizos": "法术伤害",
    "healing power": "治疗效果", "poder de curación": "治疗效果",
    "critical strike": "爆击", "golpe crítico": "爆击",
    "crit": "爆击", "crítico": "爆击",
    "hit chance": "命中几率", "probabilidad de golpe": "命中几率",
    "hit rating": "命中等级", "rating de golpe": "命中等级",
    "hit percentage": "命中百分比", "porcentaje de golpe": "命中百分比",
    "hit cap": "命中上限", "cap de hit": "命中上限",
    "expertise": "精准", "pericia": "精准",
    "expertise cap": "精准上限", "cap de expertise": "精准上限",
    "dodge": "躲闪", "esquivar": "躲闪",
    "parry": "招架", "parada": "招架",
    "block": "格挡", "bloqueo": "格挡",
    "defense": "防御", "defensa": "防御",
    "defense cap": "防御上限", "defensa cap": "防御上限",
    "armor": "护甲", "armadura": "护甲",
    "spell penetration": "法术穿透", "penetración arcana": "法术穿透",
    "casting speed": "施法速度", "velocidad de lanzamiento": "施法速度",
    "attack speed": "攻击速度", "velocidad de ataque": "攻击速度",
    "armor penetration": "护甲穿透", "reducción de armadura": "护甲穿透", "arpen": "护甲穿透",
    "fire resistance": "火焰抗性", "resistencia al fuego": "火焰抗性",
    "frost resistance": "冰霜抗性", "resistencia a escarcha": "冰霜抗性",
    "nature resistance": "自然抗性", "resistencia a naturaleza": "自然抗性",
    "arcane resistance": "奥术抗性", "resistencia arcana": "奥术抗性",
    "shadow resistance": "暗影抗性", "resistencia a sombras": "暗影抗性",
    "health regeneration": "生命恢复", "regeneración de vida": "生命恢复",
    "mana regeneration": "法力恢复", "regeneración de maná": "法力恢复",
    "mana per 5 seconds": "每5秒恢复法力", "mp5": "每5秒恢复法力", "maná por 5": "每5秒恢复法力",
    "haste": "急速", "rapidez": "急速",
    "healing bonus": "治疗加成", "bonus de sanación": "治疗加成",
    "bonus": "加成", "bonificación": "加成",

    # Profesiones
    "alchemy": "炼金术", "alquimia": "炼金术",
    "herbalism": "采药", "herboristería": "采药", "herboristeria": "采药",
    "mining": "采矿", "minería": "采矿", "mineria": "采矿",
    "blacksmithing": "锻造", "herrería": "锻造", "herreria": "锻造",
    "engineering": "工程学", "ingeniería": "工程学", "ingenieria": "工程学",
    "enchanting": "附魔", "encantamiento": "附魔",
    "leatherworking": "制皮", "peletería": "制皮", "peleteria": "制皮",
    "tailoring": "裁缝", "sastrería": "裁缝", "sastreria": "裁缝",
    "cooking": "烹饪", "cocina": "烹饪",
    "fishing": "钓鱼", "pesca": "钓鱼",
    "first aid": "急救", "primeros auxilios": "急救",
    "gathering": "采集", "recolección": "采集",
    "crafting": "制造", "crafteo": "制造",
    "level profession": "提升专业", "subir profesión": "提升专业",
    "max profession": "满级专业", "maxear profesión": "满级专业",
    "master of": "大师", "maestro en": "大师",
    "learn recipe": "学习配方", "aprender receta": "学习配方",
    "enchanting recipe": "附魔配方", "receta de encantamiento": "附魔配方",
    "alchemy recipe": "炼金配方", "receta de alquimia": "炼金配方",
    "tailoring pattern": "裁缝图样", "patrón de sastrería": "裁缝图样",
    "blacksmithing plans": "锻造设计图", "diseño de herrería": "锻造设计图",

    # Materiales / Recursos
    "linen cloth": "亚麻布", "paño de lino": "亚麻布",
    "wool cloth": "毛料", "paño de lana": "毛料",
    "silk cloth": "丝绸", "paño de seda": "丝绸", "tela de seda": "丝绸",
    "mageweave cloth": "魔纹布", "paño de tejido de magia": "魔纹布",
    "runecloth": "符文布", "paño rúnico": "符文布",
    "copper ore": "铜矿", "mineral de cobre": "铜矿",
    "tin ore": "锡矿", "mineral de estaño": "锡矿",
    "iron ore": "铁矿", "mineral de hierro": "铁矿",
    "gold ore": "金矿", "mineral de oro": "金矿",
    "mithril ore": "秘银矿", "mineral de mitril": "秘银矿",
    "thorium ore": "瑟银矿", "mineral de torio": "瑟银矿",
    "copper bar": "铜锭", "barra de cobre": "铜锭",
    "bronze bar": "青铜锭", "barra de bronce": "青铜锭",
    "iron bar": "铁锭", "barra de hierro": "铁锭",
    "steel bar": "钢锭", "barra de acero": "钢锭",
    "mithril bar": "秘银锭", "barra de mitril": "秘银锭",
    "thorium bar": "瑟银锭", "barra de torio": "瑟银锭",
    "arcanite bar": "奥金锭", "barra de arcanita": "奥金锭",
    "arcanite transmute": "转化奥金", "transmutación de arcanita": "转化奥金",
    "light leather": "轻皮", "cuero ligero": "轻皮",
    "medium leather": "中皮", "cuero medio": "中皮",
    "heavy leather": "重皮", "cuero pesado": "重皮",
    "thick leather": "厚皮", "cuero grueso": "厚皮",
    "rugged leather": "硬甲皮", "cuero basto": "硬甲皮",
    "heavy hide": "重型重皮", "cuero óseo": "重型重皮",
    "dragonscales": "龙鳞", "escamas de dragón": "龙鳞",
    "dragonkin scales": "龙人鳞片", "escamas de dragonkin": "龙人鳞片",
    "black dragonscales": "黑色龙鳞", "escamas negras de dragón": "黑色龙鳞",
    "thick crocodile skin": "厚鳄鱼皮", "cuero de cocodrilo": "厚鳄鱼皮",
    "peacebloom": "宁神花", "raíz de peacebloom": "宁神花",
    "hoja de plata": "银叶草", "silverleaf": "银叶草",
    "raíz de tierra": "地根草", "earthroot": "地根草",
    "real del mago": "魔皇草", "mageroyal": "魔皇草",
    "zarza": "石南草", "briarthorn": "石南草",
    "hierba moreteada": "跌打草", "bruiseweed": "跌打草",
    "flor de acero salvaje": "野钢花", "wild steelbloom": "野钢花",
    "sangre de grom": "格罗姆之血", "gromsblood": "格罗姆之血",
    "veneno del rey": "皇血草", "kingsbane": "皇血草",
    "arthas' tears": "阿尔萨斯之泪", "arthas lágrimas": "阿尔萨斯之泪",
    "hierba solar": "太阳草", "sungrass": "太阳草",
    "hierba ciega": "盲目草", "blindweed": "盲目草",
    "flor de la plaga": "瘟疫花", "plaguebloom": "瘟疫花",
    "salvia de plata de montaña": "山鼠草", "mountain silversage": "山鼠草",
    "gorrocelo": "冰盖草", "icecap": "冰盖草",
    "hoja de sueño": "梦叶草", "dreamfoil": "梦叶草",
    "firebloom": "火焰花", "flor de azafrán": "火焰花", "flor del fuego": "火焰花",
    "nexus crystal": "联结水晶", "cristal de nexo": "联结水晶",
    "lesser eternal essence": "次级永恒精华", "esencia astuta": "次级永恒精华", "esencia eterna menor": "次级永恒精华",
    "greater eternal essence": "强效永恒精华", "esencia eterna mayor": "强效永恒精华",
    "lesser mystic essence": "次级神秘精华", "astilla misteriosa menor": "次级神秘精华",
    "dream dust": "幻境尘", "polvo de oscuridad": "幻境尘",
    "illusion dust": "幻影尘", "polvo de maravilla": "幻影尘", "esencia la ilusión": "幻影尘",
    "soul shard": "灵魂碎片", "fragmento de alma": "灵魂碎片",
    "shadow shard": "暗影碎片", "fragmento de sombra": "暗影碎片",
    
    # Consumibles
    "healing potion": "治疗药水", "pocion de vida": "治疗药水",
    "mana potion": "法力药水", "pocion de mana": "法力药水",
    "major mana potion": "强效法力药水", "pocion de maná mayor": "强效法力药水",
    "major healing potion": "强效治疗药水", "pocion de vida mayor": "强效治疗药水",
    "swiftness potion": "迅捷药水", "pocion de velocidad": "迅捷药水",
    "frost protection potion": "冰霜防护药水", "pocion de escarcha": "冰霜防护药水",
    "fire protection potion": "火焰防护药水", "pocion de fuego": "火焰防护药水",
    "nature protection potion": "自然防护药水", "pocion de naturaleza": "自然防护药水",
    "shadow protection potion": "暗影防护药水", "pocion de sombras": "暗影防护药水",
    "arcane protection potion": "奥术防护药水", "pocion arcana": "奥术防护药水",
    "elixir of giants": "巨人药剂", "elixir del gigante": "巨人药剂",
    "elixir of the mongoose": "猫鼬药剂", "elixir del mongoose": "猫鼬药剂", "elixir de la mangosta": "猫鼬药剂",
    "elixir of greater intellect": "强效智力药剂", "elixir de inteligencia": "强效智力药剂",
    "elixir of greater wisdom": "强效智慧药剂", "elixir del sabio": "强效智慧药剂",
    "flask of supreme power": "超级能量合剂", "frasco de supremacía": "超级能量合剂",
    "flask of the titans": "泰坦合剂", "frasco del titán": "泰坦合剂",
    "flask of distilled wisdom": "精炼智慧合剂", "frasco de destilación": "精炼智慧合剂",
    "flask of chromatic resistance": "多彩抗性合剂", "frasco de resistencia": "多彩抗性合剂",
    "buff food": "属性食物", "comida de buff": "属性食物",
    "agility food": "敏捷食物", "comida con agilidad": "敏捷食物",
    "strength food": "力量食物", "comida con fuerza": "力量食物",
    "spirit food": "精神食物", "comida con espíritu": "精神食物",
    "grilled squid": "烤鱿鱼", "gamba asada": "烤鱿鱼",
    "baked bass": "烤大嘴鲈鱼", "pescado asado": "烤大嘴鲈鱼",
    "runecloth bandage": "符文布绷带", "venda de tejido rúnico": "符文布绷带",
    "heavy runecloth bandage": "厚符文布绷带", "venda pesada de rúnico": "厚符文布绷带",
    "mana dust": "法力粉尘", "polvo de mana": "法力粉尘",
    "shadow dust": "暗影粉尘", "tierra de sombra": "暗影粉尘",

    # PvP / Rangos Militares
    "private": "列兵", "soldado raso": "列兵",
    "corporal": "下士", "cabo": "下士",
    "sergeant": "中士", "sargento alianza": "中士",
    "master sergeant": "军士长", "sargento maestro": "军士长",
    "sergeant major": "精锐军士长", "sargento mayor alianza": "精锐军士长",
    "knight": "骑士", "caballero": "骑士",
    "knight-lieutenant": "少尉", "caballero teniente": "少尉",
    "knight-captain": "大尉", "caballero capitán": "大尉",
    "knight-champion": "少校", "caballero campeón": "少校",
    "lieutenant commander": "中校", "teniente comandante": "中校",
    "commander": "司令", "comandante": "司令",
    "marshal": "元帅", "mariscal": "元帅",
    "field marshal": "陆军元帅", "mariscal de campo": "陆军元帅",
    "grand marshal": "大元帅", "gran mariscal": "大元帅",
    "scout": "斥候", "zalamero": "斥候",
    "grunt": "步兵",
    "stone guard": "石卫士", "guardia de piedra": "石卫士",
    "blood guard": "血卫士", "guardia de sangre": "血卫士",
    "legionnaire": "军团士兵", "legionario": "军团士兵",
    "centurion": "百夫长", "centurión": "百夫长",
    "champion": "勇士", "campeón horda": "勇士",
    "lieutenant general": "将军", "teniente general": "将军",
    "general": "督军", "general horda": "督军",
    "warlord": "战歌督军", "señor de la guerra": "督军",
    "high warlord": "高阶督军", "alto señor de la guerra": "高阶督军",
    "warsong gulch": "战歌峡谷", "garganta grito de guerra": "战歌峡谷",
    "arathi basin": "阿拉希盆地", "cuenca de arathi": "阿拉希盆地",
    "alterac valley": "奥特兰克山谷", "valle de alterac": "奥特兰克山谷",
    "eye of the storm": "风暴之眼", "ojo de la tormenta": "风暴之眼",
    "battleground": "战场", "campo de batalla": "战场",
    "battleground queue": "战场排队", "cola de campo de batalla": "战场排队",
    "honor points": "荣誉点数", "puntos de honor": "荣誉点数",
    "arena points": "竞技场点数", "puntos de arena": "竞技场点数",
    "our flag": "我们的旗帜", "nuestra bandera": "我们的旗帜",
    "their flag": "他们的旗帜", "su bandera": "他们的旗帜",
    "cap flag": "开旗", "capturar bandera": "开旗",
    "flag was taken": "旗帜被夺", "la bandera fue tomada": "旗帜被夺",
    "flag on ground": "旗帜落地", "bandera en suelo": "旗帜落地",
    "flag returned": "旗帜归位", "bandera devuelta": "旗帜归位",
    "defend base": "防守基地", "defender base": "防守基地",
    "cap base": "开旗", "capturar base": "开旗",
    "stables": "马厩", "establos de arathi": "马厩",
    "farm": "农场", "granja de arathi": "农场",
    "goldmine": "金矿", "mina de arathi": "金矿",
    "lumber mill": "伐木场", "aserradero de arathi": "伐木场",
    "blacksmith": "铁匠铺", "herrería de arathi": "铁匠铺",
    "alterac towers": "奥特兰克哨塔", "torres de alterac": "奥特兰克哨塔",
    "stonehearth bunker": "石炉碉堡", "fuerte norteño": "石炉碉堡",
    "snowfall graveyard": "落雪墓地", "fuerte sureño": "落雪墓地",
    "drek's fortress": "霜狼要塞", "fortaleza de drek": "霜狼要塞",
    "van's fortress": "雷矛要塞", "fortaleza de van": "雷矛要塞",

    # Geografía Azeroth
    "stormwind": "暴风城", "ventormenta": "暴风城",
    "stormwind gate": "暴风城大门", "entrada a ventormenta": "暴风城大门",
    "stormwind city": "暴风城", "ciudad de ventormenta": "暴风城",
    "stormwind mages": "暴风城法师", "magos de ventormenta": "暴风城法师",
    "ironforge": "铁炉堡", "forjaz": "铁炉堡",
    "darnassus": "达纳苏斯",
    "cathedral of light": "光明大教堂", "catedral de la luz": "光明大教堂",
    "mage quarter": "法师区", "barrio de los magos": "法师区",
    "the drunken dwarf": "醉酒的矮人", "el enano borracho": "醉酒的矮人",
    "orgrimmar": "奥格瑞玛",
    "thunder bluff": "雷霆崖", "cima del trueno": "雷霆崖",
    "undercity": "幽暗城", "entrañas": "幽暗城",
    "moonglade": "月光林地", "claro de la luna": "月光林地",
    "elwynn forest": "艾尔文森林", "bosque de elwynn": "艾尔文森林",
    "westfall": "西部荒野", "páramos de poniente": "西部荒野",
    "redridge mountains": "赤脊山", "montañas cresta roja": "赤脊山",
    "duskwood": "暮色森林", "bosque del ocaso": "暮色森林",
    "booty bay": "藏宝海湾", "bahía del botín": "藏宝海湾",
    "ratchet": "棘齿城", "trinquete": "棘齿城",
    "wax window": "蜡质窗户", "ventana de cera": "蜡质窗户",
    "eastern plaguelands": "东瘟疫之地", "tierras de la peste este": "东瘟疫之地",
    "western plaguelands": "西瘟疫之地", "tierras de la peste oeste": "西瘟疫之地",
    "eastern kingdoms": "东部王国", "montañas del este": "东部王国",
    "the hinterlands": "辛特兰", "hinterlands": "辛特兰",
    "arathi highlands": "阿拉希高地", "tierras altas de arathi": "阿拉希高地", "cordillera de arathi": "阿拉希高地",
    "badlands": "荒芜之地",
    "the lowlands": "低地", "las tierras bajas": "低地",
    "ashenvale": "灰谷", "valle de fresno": "灰谷",
    "blasted lands": "诅咒之地", "tierras devastadas": "诅咒之地",
    "deadwind pass": "逆风小径", "paso de la muerte": "逆风小径",
    "feralas": "菲拉斯",
    "desolace": "凄凉之地",
    "tanaris": "塔纳利斯",
    "silithus": "希利苏斯",
    "firelands": "火焰之地", "tierras de fuego": "火焰之地",
    "ashenvale plains": "灰谷平原", "llanuras de cenizas": "灰谷平原",
    "winterspring": "冬泉谷", "cuna del invierno": "冬泉谷",
    "un'goro crater": "安戈洛环形山", "un'goro": "安戈洛环形山", "cazoleta de un'goro": "安戈洛环形山",
    "zangarmarsh": "赞加沼泽",
    "peninsula del fuego infernal": "地狱火半岛", "hellfire peninsula": "地狱火半岛",
    "flight point": "飞行点", "punto de vuelo": "飞行点",
    "flight master": "飞行管理员", "maestra de vuelo": "飞行管理员",
    "take the flight path": "坐飞机", "vuelo al punto": "坐飞机",
    "taking the flight path": "坐飞机中", "voy en vuelo": "坐飞机中",
    "hearthstone": "炉石", "piedra de hogar": "炉石",
    "hearthstoned here?": "炉石在这吗?", "tienes hearthstone aquí": "炉石在这吗?",
    "hearthstone in sw": "炉石暴风城", "ho en ventormenta": "炉石暴风城",
    "hearthstone in org": "炉石奥格", "ho en org": "炉石奥格",
    "summoning stone": "拉人石", "punto de invocación": "拉人石",
    "near the stone": "在石头旁", "cerca de la piedra": "在石头旁",

    # Turtle WoW Contenido
    "rest tent": "帐篷", "carpa de descanso": "帐篷",
    "tent": "帐篷", "tienda de campaña": "帐篷", "carpa": "帐篷",
    "tents": "帐篷", "carpas": "帐篷",
    "any tents here?": "有帐篷吗?", "hay carpas aquí": "有帐篷吗?",
    "rested xp bonus": "双倍经验奖励", "bono de descanso": "双倍经验奖励",
    "rested xp": "双倍经验", "xp de descanso": "双倍经验",
    "i am rested": "我有双倍", "estoy descansado": "我有双倍",
    "hardcore": "硬核",
    "hardcore mode": "硬核模式", "modo hardcore": "硬核模式",
    "hardcore challenge": "硬核挑战", "desafío hardcore": "硬核挑战",
    "died permanently": "一命通关结束", "murió para siempre": "一命通关结束",
    "lost their character": "失去了角色", "perdió su personaje": "失去了角色",
    "press f": "扣F", "f en el chat": "扣F",
    "cheer up": "振作起来", "ánimo": "振作起来",
    "donated to turtle wow": "赞助了乌龟服", "donado a turtle wow": "赞助了乌龟服",
    "server donation": "赞助服务器", "donación al servidor": "赞助服务器",
    "private server": "私服", "servidor privado": "私服",
    "turtle wow": "乌龟服",
    "ghostlands": "幽魂之地", "tierras fantasmas": "幽魂之地",
    "emerald dream": "翡翠梦境", "sueño esmeralda": "翡翠梦境",
    "tel'abim isle": "泰拉比姆岛", "isla de tel'abim": "泰拉比姆岛",
    "tel'abim": "泰拉比姆", "telabim": "泰拉比姆",
    "hiraeth": "海勒斯堡", "hiraeth keep": "海勒斯堡",
    "slow and steady": "慢而稳", "lento y constante": "慢而稳",
    "vagrant": "流浪者", "vagabundo en turtle": "流浪者",
    "no inns used": "禁用旅店", "sin usar posada": "禁用旅店",
    "free respec": "免费洗天赋", "spec gratis": "免费洗天赋",

    # Administración Guild / Raid
    "guild": "公会", "hermandad": "公会",
    "guild master": "会长", "maestro de hermandad": "会长",
    "officer": "官员", "oficial de guild": "官员",
    "recruit": "招募", "recluta": "招募",
    "guild member": "公会成员", "miembro de guild": "公会成员",
    "attunement": "开门任务", "armonización": "开门任务", "armonizado": "已做开门", "attuned": "已做开门",
    "not attuned": "没做开门", "no armonizado": "没做开门",
    "is attuned": "有资格", "tiene la armonización": "有资格",
    "needs attunement": "需要开门", "necesita armonización": "需要开门",
    "durability": "耐久度", "durabilidad": "耐久度",
    "low durability": "低耐久度", "durabilidad baja": "低耐久度",
    "repair your gear": "修理装备", "repara equipo": "修理装备",
    "repair before the pull": "开怪前修理", "reparar antes del pull": "开怪前修理",
    "field repair bot": "修理机器人", "reparador de combate": "修理机器人", "robot reparador": "修理机器人",
    "dungeon": "地下城", "mazmorra": "地下城",
    "dungeons": "地下城", "mazmorras": "地下城",
    "40 man raid": "40人团", "raid de 40 personas": "40人团",
    "20 man raid": "20人团", "raid de 20 personas": "20人团",
    "10 man raid": "10人团", "raid de 10 personas": "10人团",
    "raid ready": "团本准备就绪", "listo para la raid": "团本准备就绪",
    "scheduled raid": "活动计划", "raid programada": "活动计划",
    "raid time": "活动时间", "hora de raid": "活动时间",
    "raid start": "活动开始", "inicio de raid": "活动开始",
    "cet": "欧洲中部时间", "hora central europea": "欧洲中部时间",
    "server time": "服务器时间", "hora del servidor": "服务器时间",
    "raid composition": "团队配置", "composición de raid": "团队配置",
    "group comp": "队伍配置", "composición de grupo": "队伍配置",
    "roster": "名单", "rostar": "名单",
    "waitlist": "替补", "lista de espera": "替补",
    "on the waitlist": "在替补席", "en lista de espera": "在替补席",
    "not on the roster": "不在名单上", "fuera del rostar": "不在名单上",
    "attendance": "出勤", "lista de asistencia": "出勤",
    "good attendance": "出勤良好", "buena asistencia": "出勤良好",
    "bad attendance": "出勤差", "mala asistencia": "出勤差",
    "kick from group": "踢出队伍", "kickear del grupo": "踢出队伍",
    "loot council": "分配委员会", "loot de consejo": "分配委员会",
    "officer loot": "官员分配",

    # Mantenimiento Party
    "low on mana": "缺蓝", "necesito maná": "缺蓝", "necesito mana": "缺蓝",
    "drinking": "喝水中", "bebiendo": "喝水中",
    "waiting for mana": "等蓝", "esperen maná": "等蓝",
    "oom": "空蓝", "sin maná": "空蓝",
    "i am oom": "我空蓝了", "estoy oom": "我空蓝了",
    "heal me": "加血", "curame": "加血",
    "cleanse me": "驱散我", "limpiame": "驱散我",
    "dispel my debuff": "驱散我", "quítame el debuff": "驱散我",
    "shield me": "给个盾", "ponme escudo": "给个盾",
    "summon me plz": "拉我一下", "invócame por favor": "拉我一下",
    "give me mage water": "给点 water", "dame agua del mago": "给点水",
    "give me mage food": "给点面包", "dame comida del mago": "给点面包",
    "summoning stone is up": "拉人石已就绪", "piedra de invocación lista": "拉人石已就绪",
    "everyone at the stone": "都来石头这", "están todos en la piedra": "都来石头`这",
    "i need a summon": "求拉", "necesito invocación": "求拉",
    "summon me to the dungeon": "拉我进本", "invócame a la mazmorra": "拉我进本",
    "ready to pull": "准备开怪", "listo para el pull": "准备开怪",
    "ready when you are": "随时可以", "empezamos cuando quieran": "随时可以",
    "pulling in": "开怪倒计时", "hacemos el pull en": "开怪倒计时",
    "pulling": "开怪", "pullcando": "开怪",
    "ready for pull": "开怪准备", "preparados para el pull": "开怪准备",
    "bad pull": "开怪失误", "pull fallido": "开怪失误",
    "lost the pull": "没拉住", "se me fue el pull": "没拉住",
    "healer has aggro": "奶妈OT了", "aggro al healer": "奶妈OT了",
    "healer is dying": "奶妈快死了", "healer está muriendo": "奶妈快死了",
    "need a rez": "求复活", "necesito rez": "求复活",
    "need a resurrection": "求复活", "néceito resurección": "求复活",
    "can you rez me": "能拉我吗", "me puedes rezar": "能拉我吗",
    "rez me": "拉我", "dame rez": "拉我",
    "regroup at stone": "石头处集合", "reu en la piedra": "石头处集合",
    "go repair": "去修理", "vayan a reparar": "去修理",
    "running out of time": "时间不够了", "queda poco tiempo": "时间不够了",
    "out of time": "没时间了", "nos hemos quedado sin tiempo": "没时间了",
    "starting again": "重新开始", "empezamos otra vez": "重新开始",
    "next pull": "下一个", "siguiente pull": "下一个",
    "straight to the boss": "直奔BOSS", "boss directo": "直奔BOSS",

    # Slots de Equipo
    "head": "头部", "cabeza": "头部",
    "neck": "颈部", "cuello": "颈部",
    "back": "背部", "espalda": "背部",
    "cloak": "披风", "capa": "披风",
    "chest": "胸部", "pecho": "胸部",
    "wrists": "手腕", "muñecas": "手腕",
    "bracers": "护腕", "brazales": "护腕",
    "hands": "手部", "manos": "手部",
    "gloves": "手套", "guantes": "手套",
    "belt": "腰带", "cinturón": "腰带",
    "legs": "腿部", "piernas": "腿部",
    "pants": "裤子", "pantalones": "裤子",
    "feet": "脚部", "pies": "脚部",
    "boots": "靴子", "botas": "靴子",
    "finger": "手指", "dedo": "手指",
    "ring": "戒指", "anillo": "戒指",
    "trinket": "饰品", "amuleto": "饰品",
    "relic": "圣物", "reliquia": "圣物",
    "off hand weapon": "副手武器", "off-hand": "副手",
    "off hand": "副手", "mano secundaria": "副手",
    "main hand": "主手", "arma principal": "主手",
    "two-handed weapon": "双手武器", "arma a dos manos": "双手武器",
    "bow": "弓", "arco": "弓",
    "crossbow": "弩", "ballesta": "弩",
    "wand": "魔杖", "vara": "魔杖",
    "sword": "单手剑", "espada": "单手剑",
    "axe": "单手斧", "hacha": "单手斧",
    "mace": "单手锤", "maza": "单手锤",
    "staff": "法杖", "bastón de magia": "法杖",
    "dagger": "匕首", "daga": "匕首",
    "polearm": "长柄武器", "lanza": "长柄武器",
    "fist weapon": "拳套", "arma de puño": "拳套",
    "shield": "盾牌", "escudo": "盾牌",
    "tier 1": "T1", "t1": "T1",
    "tier 2": "T2", "t2": "T2",
    "tier 3": "T3", "t3": "T3",
    "tier 1 set": "T1套装", "set de tier uno": "T1套装",
    "tier 2 set": "T2套装", "set de tier dos": "T2套装",
    "tier 3 set": "T3套装", "set de tier tres": "T3套装",
    "set piece": "套装部位", "pieza de set": "套装部位",
    "set bonus": "套装属性", "bono de set": "套装属性",
    "epic item": "史诗物品", "objeto épico": "史诗物品",
    "rare item": "精良物品", "objeto raro": "精良物品",
    "uncommon item": "优秀物品", "objeto poco común": "优秀物品",
    "legendary item": "传说物品", "objeto legendario": "传说物品",
    "épico": "史诗", "purple": "史诗",
    "legendary": "传说", "naranja": "传说",
    "rare": "精良", "azul": "精良",
    "uncommon": "优秀", "verde": "优秀",
    "poor": "粗糙", "gris": "粗糙",
    "common loot": "普通掉落", "blanco loot": "普通掉落",
    "pre best in slot": "P5毕业前过渡", "pre-bis": "P5毕业前过渡",
    "best in slot": "毕业装备", "bis": "毕业装备", "mejor pieza posible": "毕业装备",
    "upgrade": "提升", "mejora": "提升",
    "not an upgrade for me": "对我没有提升", "no es mejora para mí": "对我没有提升",
    "it's an upgrade for me": "对我是提升", "es mejora para mí": "对我是提升",

    # Misiones / Progresión
    "quest": "任务", "misión": "任务",
    "quests": "任务", "misiones": "任务",
    "quest log": "任务日志", "registro de misiones": "任务日志",
    "complete quest": "完成任务", "completar misión": "完成任务",
    "turn in quest": "交任务", "entregar misión": "交任务",
    "quest reward": "任务奖励", "recompensa de misión": "任务奖励",
    "chain quest": "系列任务", "misión de cadena": "系列任务",
    "raid quest": "团本任务", "misión de raid": "团本任务",
    "elite quest": "精英任务", "misión de élite": "精英任务",
    "daily quest": "日常任务", "misión diaria": "日常任务",
    "weekly quest": "周常任务", "misión semanal": "周常任务",
    "reputation": "声望", "reputación": "声望", "rep": "声望",
    "neutral": "中立",
    "friendly": "友好", "amistoso": "友好",
    "honored": "尊敬", "honorable": "尊敬",
    "revered": "敬重", "reverenciado": "敬重",
    "exalted": "崇拜", "exaltado": "崇拜",
    "hated": "仇恨", "odiado": "仇恨",
    "hostile": "敌对", "hostil": "敌对",
    "grind reputation": "刷声望", "grindear reputación": "刷声望",
    "rep grind": "刷声望", "grindear rep": "刷声望",
    "experience": "经验", "experiencia": "经验", "xp": "经验",
    "level": "等级", "nivel": "等级",
    "level up": "升级", "subir nivel": "升级",
    "subí de nivel": "升级了", "dinged": "升级了", "ding": "升级了",
    "welcome to level 60": "欢迎来到60级", "bienvenido al nivel 60": "欢迎来到60级",
    "hit max level": "满级了", "llegar al máximo": "满级了",
    "max level": "最高等级", "nivel máximo": "最高等级",
    "at level 60": "在60级", "al 60": "在60级",
    "mount": "坐骑", "montura": "坐骑",
    "60 percent mount": "小马", "75 de montura": "小马",
    "100 percent mount": "大马", "100 de montura": "大马",
    "epic mount": "千金马", "montura épica": "千金马",

    # Etiqueta Social
    "tyvm for the group": "谢谢队伍", "muchas gracias por el grupo": "谢谢队伍",
    "gl with drops": "祝你好运", "buena suerte con los drops": "祝你好运",
    "gz on the level": "恭喜升级", "felicidades por el nivel": "恭喜升级",
    "gz on the achievement": "恭喜成就", "felicidades por el logro": "恭喜成就",
    "grats": "恭喜", "felicidades": "恭喜",
    "have a nice day": "祝 তুমি hoy hoy", "have a nice day": "祝你今天过得愉快", "que tengas un buen dia": "祝你今天过得愉快",
    "have a good night": "祝你今晚过得愉快", "que pases una buena noche": "祝你今晚过得愉快",
    "get some rest": "多休息", "que descanses": "多休息",
    "take care": "保重", "cuídate": "保重",
    "greetings": "你好", "saludos": "你好",
    "greetings everyone": "大家好", "saludos a todos": "大家好",
    "see you in game": "游戏中见", "nos vemos en el juego": "游戏中见",
    "see you soon": "回头见", "hasta pronto": "回头见",
    "let's play tomorrow": "明天一起玩", "mañana jugamos": "明天一起玩",
    "that was fun": "挺有趣的", "fue divertido": "挺有趣的",
    "bad day to play": "今天不适合玩游戏", "mal día para jugar": "今天不适合玩游戏",
    "i'm tilted": "我心态炸了", "estoy tilteado": "我心态炸了",
    "gotta take a break": "我得去休息了", "me toca descansar": "我得去休息了",
    "thanks for the raid": "谢谢活动", "gracias por la raid": "谢谢活动",
    "nice pull": "拉得漂亮", "buen pull": "拉得漂亮",
    "good attempt": "尽力了", "buen intento": "尽力了",
    "so close": "太可惜了", "casi lo logramos": "太可惜了",
    "next time": "下次一定", "la próxima vez": "下次一定",
    "destiny has us in mind": "缘分啊", "el destino nos tiene en mente": "缘分啊",

    # Emotes / Expresiones
    "lol": "哈哈哈", "jajaja": "哈哈哈",
    "lmao": "笑死我了", "muerto de risa": "笑死我了",
    "so funny": "太搞笑了", "que gracioso": "太搞笑了",
    "you make me laugh": "你把我逗笑了", "me haces reír": "你把我逗笑了",
    "no way": "不可能", "no puede ser": "不可能",
    "impressive": "厉害", "impresionante": "厉害",
    "incredible": "牛逼", "increíble": "牛逼",
    "sick": "牛逼", "brutal": "牛逼",
    "oh my god": "我的天啊", "dios mío": "我的天啊",
    "oh no": "噢不", "ay no": "噢不",
    "that's a shame": "太遗憾了", "qué lastima": "太遗憾了",
    "what a shame": "太遗憾了", "qué pena": "太遗憾了",
    "awesome": "太棒了", "buenísimo": "太棒了",
    "great": "好极了", "genial": "好极了",
    "extraordinary": "非凡的", "extraordinario": "非凡的",
    "classic": "经典", "clásico": "经典",
    "what a moment": "太震撼了", "qué momento": "太震撼了",
    "that hurts": "好痛", "eso duele": "好痛",
    "noooo": "不啊", "nooo": "不啊",
    "yesss": "耶", "siii": "耶",
    "that was nice": "干得漂亮", "eso estuvo bien": "干得漂亮",
    "bad play": "失误了", "mal jugado": "失误了",
    "well played": "打得好", "bien jugado": "打得好",
    "never get tired of this": "永远玩不腻", "nunca me canso de esto": "永远玩不腻",
    "first time": "第一次", "primera vez": "第一次",
    "never seen this before": "见所未见", "nunca lo había visto": "见所未见",
    "so lucky": "运气太好了", "qué suerte": "运气太好了",
    "so unlucky": "运气太差了", "qué mala suerte": "运气太差了",
    "amazing drop": "大红手", "drop increíble": "大红手",
    "nothing dropped": "黑手", "no cayó nada": "黑手",
    "damn rng": "垃圾随机机制", "maldito rng": "垃圾随机机制",
    "rng hates me": "发牌员针对我", "el rng no me quiere": "发牌员针对我",

    # Juego / UI / Addon
    "addon": "插件",
    "user interface": "界面", "interfaz de usuario": "界面",
    "lag": "卡",
    "latency": "延迟", "latencia": "延迟",
    "ping": "网络延迟",
    "disconnected": "掉线", "desconectado": "掉线", "dc": "掉线",
    "got disconnected": "掉线了", "se desconectó": "掉线了",
    "game crashed": "游戏闪退", "crasheó el juego": "游戏闪退",
    "low fps": "掉帧", "bajo fps": "掉帧",
    "i'm frozen": "我画面冻结了", "estoy congelado": "我画面冻结了",
    "i'm lagging": "我卡了", "me lageo": "我卡了",
    "game bug": "游戏BUG", "bug del juego": "游戏BUG",
    "server error": "服务器错误", "error del servidor": "服务器错误",
    "server crash": "服务器宕机", "caída del servidor": "服务器宕机",
    "server maintenance": "服务器维护", "mantenimiento del servidor": "服务器维护",
    "server restart": "服务器重启", "reinicio del servidor": "服务器重启",
    "report a bug": "反馈BUG", "reportar un bug": "反馈BUG",
    "action bar": "动作条", "barra de acción": "动作条",
    "health bar": "生命条", "barra de salud": "生命条",
    "mana bar": "法力条", "barra de maná": "法力条",
    "energy bar": "能量条", "barra de energía": "能量条",
    "rage bar": "怒气条", "barra de rabia": "怒气条",
    "unit frames": "头像框架", "marcos de unidad": "头像框架",
    "player frame": "玩家头像", "marco del jugador": "玩家头像",
    "target frame": "目标头像", "marco del objetivo": "目标头像",
    "world map": "世界地图", "mapa del mundo": "世界地图",
    "minimap": "小地图",
    "character sheet": "角色面板", "hoja de personaje": "角色面板",
    "talent tree": "天赋树", "árbol de talentos": "天赋树",
    "talents": "天赋",
    "respec": "洗天赋", "respeccear": "洗天赋",
    "reset talents": "重置天赋", "resetear talentos": "重置天赋",
    "spellbook": "技能书", "libro de hechizos": "技能书",
    "abilities": "技能", "habilidades": "技能",
    "bag": "背包", "bolsa": "背包",
    "backpack": "双肩包", "mochila": "双肩包",
    "bags are full": "背包满了", "inventario lleno": "背包满了", "bolsas llenas": "背包满了",
    "need bigger bags": "需要大包", "necesito bolsas más grandes": "需要大包",
    "vendor": "商人", "vendedor": "商人",
    "buy mats": "买材料", "comprar materiales": "买材料",
    "sell junk": "卖垃圾", "vender basura": "卖垃圾",
    "sell all grey": "一键卖灰", "vender todo gris": "一键卖灰",
    "repair gear": "修装备", "reparar equipo": "修装备",
    "macros": "宏",
    "game settings": "设置", "configuracion del juego": "设置",
    "music volume": "音乐音量", "volumen de música": "音乐音量",
    "sfx volume": "音效音量", "volumen de efectos": "音效音量",
    "screenshot": "截图", "captura de pantalla": "截图",
    "take screenshot": "截图", "sacar foto": "截图",

    # Números / Cantidades
    "1 more": "缺一", "uno más": "缺一",
    "2 more": "缺二", "dos más": "缺二",
    "3 more": "缺三", "tres más": "缺三",
    "4 more": "缺四", "cuatro más": "缺四",
    "5 more": "缺五", "cinco más": "缺五",
    "we are progressing": "开荒中", "estamos en progresión": "开荒中",
    "first kill": "首杀", "primer kill": "首杀",
    "new record": "新纪录", "nuevo récord": "新纪录",
    "server record": "服务器纪录", "record del servidor": "服务器纪录",
    "guild record": "公会纪录", "record de guild": "公会纪录",
    "100k gold": "十万金", "cien mil de oro": "十万金",
    "1k gold": "千金", "mil de oro": "千金",
    "100 gold": "百金", "cien de oro": "百金",
    "how much gold": "多少金币", "cuánto oro": "多少金币",
    "weekly gold": "周金", "oro de la semana": "周金",
    "repair costs": "修理费", "costos de reparación": "修理费",
}

with open(dict_path, "r", encoding="utf-8") as f:
    content = f.read()

# Patrón para identificar llamadas add de cualquier tipo capturando SOLO add(
# Esto evitará tragar los espacios y saltos de línea anteriores a add(
pattern = re.compile(r'(add\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*(?:,\s*"([^"]*)")?\s*\))')

def get_best_zh(es, en):
    es_key = es.lower().strip()
    en_key = en.lower().strip()
    
    # PRIORIDAD 1: Clave en español (evita colisiones por palabras ambiguas del inglés)
    if es_key in zh_db:
        return zh_db[es_key]
        
    # PRIORIDAD 2: Clave en inglés
    if en_key in zh_db:
        return zh_db[en_key]
        
    return None

def replacer(match):
    full_call = match.group(1)
    es = match.group(2)
    en = match.group(3)
    existing_zh = match.group(4)
    
    # Caso especial preventivo para evitar traducciones incorrectas de "back"
    if es.lower().strip() in ["regresé", "estoy de vuelta"]:
        existing_zh = "我回来了"
    
    # Si ya tiene una traducción en chino no vacía, conservarla y alinear
    if existing_zh and existing_zh.strip():
        es_part = f'"{es}",'
        en_part = f'"{en}",'
        zh_part = f'"{existing_zh}"'
        
        spaces_es = 42 - len(es_part)
        if spaces_es < 1: spaces_es = 1
        
        spaces_en = 38 - len(en_part)
        if spaces_en < 1: spaces_en = 1
        
        return f'add({es_part}{" " * spaces_es}{en_part}{" " * spaces_en}{zh_part})'
        
    # Si no tiene traducción, buscarla
    best_zh = get_best_zh(es, en)
    if best_zh:
        es_part = f'"{es}",'
        en_part = f'"{en}",'
        zh_part = f'"{best_zh}"'
        
        spaces_es = 42 - len(es_part)
        if spaces_es < 1: spaces_es = 1
        
        spaces_en = 38 - len(en_part)
        if spaces_en < 1: spaces_en = 1
        
        return f'add({es_part}{" " * spaces_es}{en_part}{" " * spaces_en}{zh_part})'
    else:
        # Si no encontramos traducción, mantener la llamada original tal como estaba (pero normalizando el formato trilingüe si es posible)
        return full_call

new_content = pattern.sub(replacer, content)

with open(dict_path, "w", encoding="utf-8") as f:
    f.write(new_content)

print("¡Procesamiento completo! Todas las llamadas add del diccionario se han alineado e inyectado manteniendo intactos los saltos de línea.")
