pfUI:RegisterModule("translator_dict", "vanilla", function ()
  -- ╔══════════════════════════════════════════════════════════════╗
  -- ║  LIBRERIA LÉXICA OFFLINE v6.0.0 — OMNI-TIER TRILINGÜE      ║
  -- ║  Motor Híbrido Hash+Greedy | ES <-> ZH <-> EN              ║
  -- ║  ~3000+ entradas | 32 categorías temáticas                 ║
  -- ╚══════════════════════════════════════════════════════════════╝

  pfUI.translator_dicts = pfUI.translator_dicts or {}
  local pairs = { "es_en", "en_es", "zh_en", "en_zh", "zh_es", "es_zh" }
  for _, p in ipairs(pairs) do
    pfUI.translator_dicts[p .. "_words"]   = pfUI.translator_dicts[p .. "_words"] or {}
    pfUI.translator_dicts[p .. "_phrases"] = pfUI.translator_dicts[p .. "_phrases"] or {}
    pfUI.translator_dicts[p .. "_keys"]    = pfUI.translator_dicts[p .. "_keys"] or {}
  end

  local function add(es, en, zh)
    local items = { {lang="es", text=es}, {lang="en", text=en}, {lang="zh", text=zh} }
    for i = 1, 3 do
      for j = 1, 3 do
        local src_lang = items[i].lang
        local dest_lang = items[j].lang
        local src_text = items[i].text
        local dest_text = items[j].text
        if i ~= j and src_text and dest_text and src_text ~= "" and dest_text ~= "" then
          local isPhrase = strfind(src_text, " ") or strfind(dest_text, " ") or strlen(src_text) > 12 or src_lang == "zh"
          local prefix = src_lang .. "_" .. dest_lang
          if isPhrase then
            if not pfUI.translator_dicts[prefix .. "_phrases"][src_text] then
              pfUI.translator_dicts[prefix .. "_phrases"][src_text] = dest_text
              table.insert(pfUI.translator_dicts[prefix .. "_keys"], src_text)
            end
          else
            pfUI.translator_dicts[prefix .. "_words"][src_text] = dest_text
          end
        end
      end
    end
  end

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 01: ABREVIATURAS DE CHAT Y SLANG        ║
  -- ╚══════════════════════════════════════════════╝
  add("afk",                         "fuera del teclado")
  add("brb",                         "vuelvo enseguida")
  add("omw",                         "en camino")
  add("lfg",                         "busco grupo")
  add("lfm",                         "busco mas")
  add("pst",                         "susurro")
  add("gg",                          "buen juego")
  add("gn",                          "buenas noches")
  add("gl",                          "buena suerte")
  add("hf",                          "que se diviertan")
  add("ty",                          "gracias")
  add("yw",                          "de nada")
  add("nvm",                         "no importa")
  add("idk",                         "no se")
  add("jk",                          "es broma")
  add("imo",                         "en mi opinion")
  add("imho",                        "en mi humilde opinion")
  add("tbh",                         "siendo honesto")
  add("ngl",                         "siendo real")
  add("lmao",                        "muerto de risa")
  add("lol",                         "jajaja")
  add("rofl",                        "revolcandome de risa")
  add("smh",                         "meneando cabeza")
  add("gg ez",                       "buen juego facil")
  add("rip",                         "descanse en paz")
  add("dw",                          "no te preocupes")
  add("np",                          "no hay problema")
  add("wb",                          "bienvenido de vuelta")
  add("cya",                         "nos vemos")
  add("gtg",                         "tengo que irme")
  add("bbl",                         "vuelvo luego")
  add("irl",                         "en la vida real")
  add("atm",                         "en este momento")
  add("fyi",                         "para tu informacion")
  add("asap",                        "lo antes posible")
  add("ez",                          "facil")
  add("nt",                          "buen intento")
  add("wp",                          "bien jugado")
  add("glhf",                        "buena suerte y que se diviertan")

  add("busco grupo",                 "lfg")
  add("buscando grupo",              "lfg")
  add("busco mas gente",             "lfm")
  add("busco un mas",                "lfm")
  add("busco healer",                "lf healer")
  add("busco tanque",                "lf tank")
  add("busco dps",                   "lf dps")
  add("busco druida",                "lf druid")
  add("busco sacerdote",             "lf priest")
  add("busco chamán",                "lf shaman")
  add("busco paladín",               "lf paladin")
  add("busco mago",                  "lf mage")
  add("busco brujo",                 "lf warlock")
  add("busco guerrero",              "lf warrior")
  add("busco pícaro",                "lf rogue")
  add("busco cazador",               "lf hunter")
  add("mandame susurro",             "pst me")
  add("dame susurro",                "pst me")
  add("susurrame",                   "pst me")
  add("invitame",                    "inv me")
  add("invítame",                    "inv me")
  add("dame inv",                    "inv me")
  add("vuelvo enseguida",            "brb")
  add("ya vengo",                    "brb")
  add("regresé",                     "back")
  add("estoy de vuelta",             "back")
  add("fuera del teclado",           "afk")
  add("en camino",                   "omw")
  add("voy para allá",               "omw")
  add("muchas gracias",              "ty vm")
  add("mil gracias",                 "tyvm")
  add("de nada",                     "yw")
  add("no importa",                  "nvm")
  add("no te preocupes",             "dw")
  add("lo siento",                   "sry")
  add("perdón",                      "sry")
  add("perdon",                      "sry")
  add("fallo mío",                   "my bad")
  add("es mi culpa",                 "my bad")
  add("lo siento es mi culpa",       "my bad sry")
  add("buenas",                      "hi")
  add("hola a todos",                "hi all")
  add("nos vemos",                   "cya")
  add("buen juego",                  "gg")
  add("buenas noches",               "gn")
  add("buena suerte",                "gl")
  add("diviértanse",                 "hf")
  add("no lo se",                    "idk")
  add("no lo sé",                    "idk")
  add("no tengo idea",               "idk")
  add("es broma",                    "jk")
  add("es una broma",                "just kidding")
  add("por supuesto",                "of course")
  add("claro que si",                "sure")
  add("tal vez",                     "maybe")
  add("quizás",                      "perhaps")
  add("quizas",                      "perhaps")
  add("entiendo",                    "i see")
  add("me parece bien",              "sounds good")
  add("estoy de acuerdo",            "i agree")
  add("de acuerdo",                  "agreed")
  add("ya sabes",                    "ya know")
  add("todo bien",                   "all good")
  add("esposo",                      "hubby")
  add("marido",                      "hubby")
  add("de vez en cuando",            "from time to time")
  add("fue un placer",               "it was a pleasure")
  add("fue un placer jugar",         "nice playing with you")
  add("mañana nos vemos",            "see you tomorrow")
  add("estoy cansado",               "i am tired")
  add("tengo que irme",              "i have to go")
  add("mi mama me llama",            "mom calls me")
  add("mi esposa me llama",          "wife calls me")
  add("igualmente",                  "same to you")
  add("supongo que no",              "i guess not")
  add("tengo lag",                   "i have lag")
  add("mi internet está mal",        "my internet is bad")
  add("esperen un momento",          "wait a sec")
  add("quién sabe",                  "who knows")
  add("alguien más",                 "anyone else")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 02: MAZMORRAS — NAMES & ACRONYMS        ║
  -- ╚══════════════════════════════════════════════╝
  add("minas de la muerte",          "deadmines")
  add("las minas",                   "deadmines")
  add("cavernas de los lamentos",    "wailing caverns")
  add("cavernas de lamentos",        "wailing caverns")
  add("guarida de la losa negra",    "blackfathom deeps")
  add("gnomeregan",                  "gnomeregan")
  add("guarida gnomeregan",          "gnome")
  add("sima ígnea",                  "ragefire chasm")
  add("sima ignea",                  "rfc")
  add("castillo colmillo oscuro",    "shadowfang keep")
  add("colmillo oscuro",             "sfk")
  add("monasterio escarlata",        "scarlet monastery")
  add("biblioteca escarlata",        "sm lib")
  add("armería escarlata",           "sm arm")
  add("catedral escarlata",          "sm cath")
  add("cementerio escarlata",        "sm gy")
  add("profundidades de rocanegra",  "blackrock depths")
  add("brd",                         "profundidades de rocanegra")
  add("cumbre superior de rocanegra","upper blackrock spire")
  add("cumbre inferior de rocanegra","lower blackrock spire")
  add("ubrs",                        "cumbre superior")
  add("lbrs",                        "cumbre inferior")
  add("zul'farrak",                  "zul'farrak")
  add("maraudon",                    "maraudon")
  add("templo sumergido",            "sunken temple")
  add("masacre de diremaul norte",   "dire maul north")
  add("masacre de diremaul este",    "dire maul east")
  add("masacre de diremaul oeste",   "dire maul west")
  add("diremaul",                    "dire maul")
  add("masacre norte",               "dm north")
  add("masacre este",                "dm east")
  add("masacre oeste",               "dm west")
  add("razas cenizas",               "razorfen kraul")
  add("razorfen kraul",              "razas cenizas")
  add("aguijón de razorfen",         "razorfen downs")
  add("razorfen downs",              "aguijon de razorfen")
  add("uldaman",                     "uldaman")
  add("zul'gurub",                   "zul'gurub")
  add("scholomance",                 "scholomance")
  add("estratolme",                  "stratholme")
  add("strat",                       "estratolme")
  add("scholo",                      "scholomance")
  add("estrato vivo",                "strat live")
  add("estrato muerto",              "strat ud")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 03: RAIDS — NAMES & ACRONYMS            ║
  -- ╚══════════════════════════════════════════════╝
  add("núcleo de magma",             "molten core")
  add("nucleo de magma",             "molten core")
  add("mc",                          "molten core")
  add("guarida alanegra",            "blackwing lair")
  add("bwl",                         "blackwing lair")
  add("guarida de onyxia",           "onyxia's lair")
  add("guarida de onixia",           "onyxia's lair")
  add("ony",                         "onyxia")
  add("naxxramas",                   "naxxramas")
  add("naxx",                        "naxxramas")
  add("ruinas de ahn'qiraj",         "ruins of ahn'qiraj")
  add("templo de ahn'qiraj",         "temple of ahn'qiraj")
  add("aq20",                        "aq 20")
  add("aq40",                        "aq 40")
  add("zul'aman",                    "zul'aman")
  add("santuario esmeralda",         "emerald sanctum")
  add("karazhan",                    "karazhan")
  add("karazhan inferior",           "lower karazhan")
  add("kara",                        "karazhan")
  add("cavernas del tiempo",         "caverns of time")
  add("pantano de las penas",        "black morass")
  add("isla de lapidis",             "lapidis isle")
  add("isla de gillijim",            "gillijim's isle")
  add("hiraeth",                     "hiraeth keep")
  add("isla de tel'abim",            "tel'abim isle")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 04: JEFES VANILLA (Boss Names ES/EN)    ║
  -- ╚══════════════════════════════════════════════╝
  -- MC Bosses
  add("lucifron",                    "lucifron")
  add("magmadar",                    "magmadar")
  add("gehennas",                    "gehennas")
  add("garr",                        "garr")
  add("baron geddon",                "baron geddon")
  add("geddon",                      "geddon")
  add("shazzrah",                    "shazzrah")
  add("sulfuron portador",           "sulfuron harbinger")
  add("golemagg el incinerador",     "golemagg the incinerator")
  add("golemagg",                    "golemagg")
  add("majordomo ejecutus",          "majordomo executus")
  add("majordomo",                   "majordomo")
  add("ragnaros",                    "ragnaros")
  add("el señor del fuego",          "the firelord")
  -- BWL Bosses
  add("razorgore el intacto",        "razorgore the untamed")
  add("razorgore",                   "razorgore")
  add("vaelastrasz el corrupto",     "vaelastrasz the corrupt")
  add("vael",                        "vaelastrasz")
  add("lashlayer braxiss",           "broodlord lashlayer")
  add("broodlord",                   "broodlord")
  add("firemaw",                     "firemaw")
  add("ebonroc",                     "ebonroc")
  add("flamegor",                    "flamegor")
  add("chromaggus",                  "chromaggus")
  add("nefarian",                    "nefarian")
  -- ZG Bosses
  add("venoxis el sacerdote serpiente","high priest venoxis")
  add("venoxis",                     "venoxis")
  add("jeklik la sacerdotisa",       "high priestess jeklik")
  add("jeklik",                      "jeklik")
  add("mar'li la sacerdotisa",       "high priestess mar'li")
  add("marli",                       "mar'li")
  add("thekal el sacerdote",         "high priest thekal")
  add("thekal",                      "thekal")
  add("arlokk la sacerdotisa",       "high priestess arlokk")
  add("arlokk",                      "arlokk")
  add("jindo el sacerdote oscuro",   "jin'do the hexxer")
  add("jindo",                       "jin'do")
  add("hakkar el alma tortuosa",     "hakkar the soulflayer")
  add("hakkar",                      "hakkar")
  -- AQ40 Bosses
  add("el profeta skeram",           "the prophet skeram")
  add("skeram",                      "skeram")
  add("reyes bug",                   "the bug trio")
  add("los tres reyes",              "the twin emperors")
  add("vek'lor",                     "vek'lor")
  add("vek'nilash",                  "vek'nilash")
  add("emperadores gemelos",         "twin emperors")
  add("c'thun",                      "c'thun")
  add("el ojo de c'thun",            "the eye of c'thun")
  -- Naxx Bosses
  add("anub'rekhan",                 "anub'rekhan")
  add("la gran viuda faerlina",      "grand widow faerlina")
  add("maexxna",                     "maexxna")
  add("noth el empestador",          "noth the plaguebringer")
  add("noth",                        "noth")
  add("heigan el impuro",            "heigan the unclean")
  add("heigan",                      "heigan")
  add("loatheb",                     "loatheb")
  add("instructor razuvious",        "instructor razuvious")
  add("gothik el segador",           "gothik the harvester")
  add("gothik",                      "gothik")
  add("los cuatro jinetes",          "the four horsemen")
  add("patchwerk",                   "patchwerk")
  add("grobbulus",                   "grobbulus")
  add("gluth",                       "gluth")
  add("thaddius",                    "thaddius")
  add("sapphiron",                   "sapphiron")
  add("kel'thuzad",                  "kel'thuzad")
  add("kel thuzad",                  "kel'thuzad")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 05: TÁCTICAS Y COMBATE                  ║
  -- ╚══════════════════════════════════════════════╝
  add("ataca mi objetivo",           "attack my target")
  add("enfoca mi objetivo",          "focus my target")
  add("ataquen mi target",           "focus my target")
  add("no ataquen",                  "don't attack")
  add("paren el daño",               "stop dps")
  add("daño suave",                  "slow dps")
  add("máximo daño",                 "full dps")
  add("explosión de daño",           "burn phase")
  add("fase de quema",               "burn phase")
  add("esperen el pull",             "wait for pull")
  add("cuidado con el agro",         "watch your aggro")
  add("tengo el agro",               "i have aggro")
  add("perdí el agro",               "lost aggro")
  add("perdi el agro",               "lost aggro")
  add("el tanque murió",             "tank is dead")
  add("necesito sanación",           "need heals")
  add("cura por favor",              "heal plx")
  add("dame buff",                   "buff me")
  add("buffs por favor",             "buffs plz")
  add("buffeame",                    "buff me")
  add("estamos listos",              "we are ready")
  add("fuera del fuego",             "out of the fire")
  add("sal del fuego",               "get out of fire")
  add("sal del area",                "get out of the aoe")
  add("no se muevan",                "don't move")
  add("quédense quietos",            "stand still")
  add("muévanse ahora",              "move now")
  add("aléjense",                    "spread out")
  add("júntense",                    "stack up")
  add("agruparse",                   "group up")
  add("peguenle al boss",            "nuke the boss")
  add("maten a los adds",            "kill the adds")
  add("maten al add",                "kill the add")
  add("limpien los adds",            "clear the adds")
  add("control de masas",            "crowd control")
  add("usa la oveja",                "sheep it")
  add("oveja al objetivo",           "sheep the target")
  add("poner oveja",                 "sheeping")
  add("usa la trampa",               "set the trap")
  add("pon trampa de hielo",         "place frost trap")
  add("usa sap",                     "sap it")
  add("usa miedo",                   "fear it")
  add("usa shackle",                 "shackle it")
  add("shackle al muerto",           "shackle the undead")
  add("hibernar a la bestia",        "hibernate the beast")
  add("usa ciclón",                  "cyclone it")
  add("usa seduce",                  "seduce it")
  add("usa banish",                  "banish it")
  add("detrás del boss",             "get behind the boss")
  add("posición detrás",             "get behind")
  add("línea de visión",             "line of sight")
  add("fuera de los",                "out of los")
  add("sin línea de visión",         "no line of sight")
  add("escóndanse",                  "take cover")
  add("corran fuera",                "run out")
  add("hacia atrás",                 "back off")
  add("retroceden",                  "fall back")
  add("reinicien",                   "reset")
  add("empezamos de nuevo",          "reset and try again")
  add("wipe",                        "nos morimos todos")
  add("hagan wipe",                  "wipe it")
  add("hacemos wipe",                "let's wipe")
  add("primer intento",              "first attempt")
  add("segundo intento",             "second attempt")
  add("tercer intento",              "third attempt")
  add("fase 1",                      "phase 1")
  add("fase 2",                      "phase 2")
  add("fase 3",                      "phase 3")
  add("fase 4",                      "phase 4")
  add("quédense ahí",                "stay there")
  add("vengan aquí",                 "come here")
  add("vénganse con el tanque",      "come to the tank")
  add("síganme",                     "follow me")
  add("pareen",                      "hold on")
  add("esperen",                     "hold on")
  add("aguanten",                    "hold your position")
  add("no entren todavía",           "don't go in yet")
  add("lista de objetivos",          "kill order")
  add("orden de muerte",             "kill order")
  add("foco en el calavera",         "focus skull")
  add("maten la calavera",           "kill skull")
  add("foco en la equis",            "focus cross")
  add("trampa a la luna",            "trap moon")
  add("oveja al cuadrado",           "sheep square")
  add("sap al triángulo",            "sap triangle")
  add("bandage",                     "venda")
  add("venda",                       "bandage")
  add("curación de emergencia",      "emergency heal")
  add("intervención de guerra",      "intercept")
  add("carga",                       "charge")
  add("provocar",                    "taunt")
  add("mockery",                     "taunt")
  add("provokar",                    "taunt")
  add("interrumpir",                 "interrupt")
  add("interrumpan el casteo",       "interrupt the cast")
  add("silencio al healer",          "silence the healer")
  add("nido de agro",                "aggro dump")
  add("resistió",                    "resisted")
  add("esquivó",                     "dodged")
  add("paró",                        "parried")
  add("bloqueó",                     "blocked")
  add("inmunidad",                   "immune")
  add("aturdido",                    "stunned")
  add("dormido",                     "sapped")
  add("enraizado",                   "rooted")
  add("congelado",                   "frozen")
  add("encadenado",                  "shackled")
  add("desafiado",                   "taunted")
  add("maldecido",                   "cursed")
  add("envenenado",                  "poisoned")
  add("enfermedad",                  "disease")
  add("maldición",                   "curse")
  add("disipar la maldición",        "remove curse")
  add("quitar el veneno",            "cure poison")
  add("quitar enfermedad",           "cure disease")
  add("disipar",                     "dispel")
  add("limpieza",                    "cleanse")
  add("limpiarme",                   "cleanse me")
  add("decursar",                    "decurse")
  add("corte de batalla",            "battle cut")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 06: MARCAS DE RAID                      ║
  -- ╚══════════════════════════════════════════════╝
  add("calavera",                    "skull")
  add("equis",                       "cross")
  add("círculo",                     "circle")
  add("luna",                        "moon")
  add("triángulo",                   "triangle")
  add("diamante",                    "diamond")
  add("cuadrado",                    "square")
  add("estrella",                    "star")
  add("pon marcas",                  "put markers")
  add("quita las marcas",            "remove markers")
  add("marca en el objetivo",        "mark the target")
  add("maten al marcado",            "kill the marked")
  add("foco en la marca",            "focus the marker")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 07: ECONOMÍA Y BOTÍN                    ║
  -- ╚══════════════════════════════════════════════╝
  add("vendo",                       "wts")
  add("compro",                      "wtb")
  add("cambio",                      "wtt")
  add("wts",                         "vendo")
  add("wtb",                         "compro")
  add("wtt",                         "cambio")
  add("se liga al equipar",          "bind on equip")
  add("se liga al recoger",          "bind on pickup")
  add("boe",                         "bind on equip")
  add("bop",                         "bind on pickup")
  add("puja mínima",                 "minimum bid")
  add("oferta inicial",              "opening bid")
  add("alguien más",                 "anyone else")
  add("a la una",                    "going once")
  add("a las dos",                   "going twice")
  add("vendido",                     "sold")
  add("todo looteado",               "all looted")
  add("reparto de oro",              "gold payout")
  add("mi parte del gdkp",           "my gdkp cut")
  add("gdkp",                        "gold dkp run")
  add("dkp",                         "dragon kill points")
  add("modo de saqueo",              "loot mode")
  add("maestro despojador",          "master looter")
  add("libre para todos",            "free for all")
  add("distribucion grupal",         "group loot")
  add("turno rotativo",              "round robin")
  add("reserva suave",               "soft reserve")
  add("reserva dura",                "hard reserve")
  add("rama principal",              "main spec")
  add("rama secundaria",             "off spec")
  add("ms os",                       "main spec off spec")
  add("solo ms",                     "main spec only")
  add("tira dados",                  "roll for it")
  add("tira un dado",                "roll")
  add("necesidad o codicia",         "need or greed")
  add("pasa el loot",                "pass on loot")
  add("desencantar",                 "disenchant")
  add("desencanta",                  "de it")
  add("desen",                       "de")
  add("barato",                      "cheap")
  add("caro",                        "expensive")
  add("precio de oferta",            "buyout price")
  add("precio de subasta",           "auction price")
  add("en subasta",                  "on ah")
  add("casa de subastas",            "auction house")
  add("subasta",                     "ah")
  add("buzón",                       "mailbox")
  add("correo en el juego",          "in-game mail")
  add("banco de hermandad",          "guild bank")
  add("más barato que la subasta",   "cheaper than ah")
  add("pagado",                      "paid out")
  add("cobrado",                     "charged")
  add("gratis",                      "free")
  add("sin cargo",                   "no charge")
  add("donacion",                    "donation")
  add("propina",                     "tip")
  add("propina incluida",            "tip included")
  add("acepto propinas",             "tips accepted")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 08: CLASES (ES->EN)                     ║
  -- ╚══════════════════════════════════════════════╝
  add("guerrero",                    "warrior")
  add("paladín",                     "paladin")
  add("paladin",                     "paladin")
  add("cazador",                     "hunter")
  add("pícaro",                      "rogue")
  add("picaro",                      "rogue")
  add("sacerdote",                   "priest")
  add("chamán",                      "shaman")
  add("chaman",                      "shaman")
  add("mago",                        "mage")
  add("brujo",                       "warlock")
  add("druida",                      "druid")
  add("warrior",                     "guerrero")
  add("paladin",                     "paladin")
  add("hunter",                      "cazador")
  add("rogue",                       "pícaro")
  add("priest",                      "sacerdote")
  add("shaman",                      "chamán")
  add("warlock",                     "brujo")
  add("druid",                       "druida")

  -- Roles
  add("tanque",                      "tank")
  add("sanador",                     "healer")
  add("curador",                     "healer")
  add("dps",                         "dps")
  add("daño",                        "damage")

  -- Specs
  add("protección",                  "protection")
  add("proteccion",                  "protection")
  add("sagrado",                     "holy")
  add("represalia",                  "retribution")
  add("sombras",                     "shadow")
  add("disciplina",                  "discipline")
  add("restauración",                "restoration")
  add("restauracion",                "restoration")
  add("elemental",                   "elemental")
  add("mejora",                      "enhancement")
  add("aflicción",                   "affliction")
  add("afliccion",                   "affliction")
  add("destrucción",                 "destruction")
  add("destruccion",                 "destruction")
  add("demonología",                 "demonology")
  add("demonologia",                 "demonology")
  add("escarcha",                    "frost")
  add("fuego",                       "fire")
  add("arcano",                      "arcane")
  add("equilibrio",                  "balance")
  add("feral",                       "feral")
  add("combate",                     "combat")
  add("asesino",                     "assassination")
  add("puntería",                    "marksmanship")
  add("punteria",                    "marksmanship")
  add("bestias",                     "beast mastery")
  add("supervivencia",               "survival")
  add("armas",                       "arms")
  add("furia guerrera",              "fury")
  add("doble especialización",       "dual spec")
  add("doble especializacion",       "dual spec")
  add("doble spec",                  "dual spec")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 09: HABILIDADES — GUERRERO              ║
  -- ╚══════════════════════════════════════════════╝
  add("golpe heroico",               "heroic strike")
  add("espiral de tormenta",         "whirlwind")
  add("remolino",                    "whirlwind")
  add("ejecutar",                    "execute")
  add("hendir armadura",             "sunder armor")
  add("grito de batalla",            "battle shout")
  add("muro de escudo",              "shield wall")
  add("represalia de guerra",        "retaliation")
  add("último aliento",              "last stand")
  add("golpe mortal",                "mortal strike")
  add("embestida",                   "charge")
  add("carga de berserker",          "berserker charge")
  add("interceptar",                 "intercept")
  add("represalia",                  "retaliation")
  add("golpe de escudo",             "shield bash")
  add("aplastar",                    "devastate")
  add("intimidar",                   "demoralizing shout")
  add("grito aterrador",             "intimidating shout")
  add("grito de batalla",            "battle shout")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 10: HABILIDADES — PALADÍN               ║
  -- ╚══════════════════════════════════════════════╝
  add("destello de luz",             "flash of light")
  add("luz sagrada",                 "holy light")
  add("sentencia",                   "judgement")
  add("escudo divino",               "divine shield")
  add("burbuja",                     "divine shield")
  add("imposición de manos",         "lay on hands")
  add("sello de justicia",           "seal of justice")
  add("sello de sabiduría",          "seal of wisdom")
  add("sello de la cruzada",         "seal of the crusader")
  add("sello de virtud",             "seal of righteousness")
  add("sello de mando",              "seal of command")
  add("pureza divina",               "divine favor")
  add("consagración",                "consecration")
  add("bendición de reyes",          "blessing of kings")
  add("bendición de sabiduría",      "blessing of wisdom")
  add("bendición de poder",          "blessing of might")
  add("bendición de salvación",      "blessing of salvation")
  add("bendición de protección",     "blessing of protection")
  add("aura de devoción",            "devotion aura")
  add("aura de retribución",         "retribution aura")
  add("aura de concentración",       "concentration aura")
  add("aura resistencia fuego",      "fire resistance aura")
  add("purificar",                   "cleanse")
  add("ira sacrada",                 "holy wrath")
  add("martillo del inquisidor",     "hammer of justice")
  add("escudo de cero",              "hammer of wrath")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 11: HABILIDADES — CAZADOR               ║
  -- ╚══════════════════════════════════════════════╝
  add("disparo de puntería",         "aimed shot")
  add("multidisparo",                "multi-shot")
  add("fingir muerte",               "feign death")
  add("marca del cazador",           "hunter's mark")
  add("aspecto del halcón",          "aspect of the hawk")
  add("aspecto del mono",            "aspect of the monkey")
  add("aspecto de bestia salvaje",   "aspect of the wild")
  add("aspecto del chacal",          "aspect of the cheetah")
  add("trampa de fuego",             "immolation trap")
  add("trampa de hielo",             "frost trap")
  add("trampa de serpiente",         "snake trap")
  add("trampa explosiva",            "explosive trap")
  add("trampa de hielo glacial",     "freezing trap")
  add("disparo de serpiente",        "serpent sting")
  add("disparo de escorpión",        "scorpid sting")
  add("disparo de víbora",           "viper sting")
  add("invocar mascota",             "call pet")
  add("liberar mascota",             "dismiss pet")
  add("alimentar mascota",           "feed pet")
  add("duelo de bestias",            "beast within")
  add("ojos de bestia",              "eyes of the beast")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 12: HABILIDADES — PÍCARO                ║
  -- ╚══════════════════════════════════════════════╝
  add("porrazo",                     "sap")
  add("golpe bajo",                  "cheap shot")
  add("golpe en los riñones",        "kidney shot")
  add("evasión",                     "evasion")
  add("esfumarse",                   "vanish")
  add("ceguera",                     "blind")
  add("veneno mortal",               "deadly poison")
  add("veneno instantáneo",          "instant poison")
  add("hemorragia",                  "hemorrhage")
  add("puñalada",                    "backstab")
  add("golpe sinérgico",             "sinister strike")
  add("ruptura",                     "rupture")
  add("rebanada y dados",            "slice and dice")
  add("exposición de armadura",      "expose armor")
  add("abanico de cuchillos",        "fan of knives")
  add("trampa de cuchillas",         "blade flurry")
  add("danza de la muerte",          "cold blood")
  add("sigilo",                      "stealth")
  add("emboscada",                   "ambush")
  add("mutilación",                  "mutilate")
  add("eviscerar",                   "eviscerate")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 13: HABILIDADES — SACERDOTE             ║
  -- ╚══════════════════════════════════════════════╝
  add("sanación superior",           "greater heal")
  add("sanación relámpago",          "flash heal")
  add("escudo de poder",             "power word: shield")
  add("burbuja del sacerdote",       "power word: shield")
  add("infusión de poder",           "power infusion")
  add("palabra oscura muerte",       "shadow word: death")
  add("palabra oscura dolor",        "shadow word: pain")
  add("mente del vuelo",             "mind flay")
  add("mente en explosión",          "mind blast")
  add("regeneración",                "renew")
  add("toque de curación",           "heal")
  add("curación circular",           "circle of healing")
  add("renacer del sacerdote",       "divine spirit")
  add("oración de fortalecimiento",  "prayer of fortitude")
  add("oración de sombra",           "prayer of shadow protection")
  add("espíritu divino",             "divine spirit")
  add("fortaleza de las sombras",    "vampiric embrace")
  add("abrazo vampírico",            "vampiric embrace")
  add("toque vampírico",             "vampiric touch")
  add("forma de sombra",             "shadowform")
  add("desvanecer",                  "fade")
  add("ánimo mayor",                 "greater heal")
  add("dispersar",                   "dispel magic")
  add("limpieza masiva",             "mass dispel")
  add("compasión divina",            "divine compassion")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 14: HABILIDADES — MAGO                  ║
  -- ╚══════════════════════════════════════════════╝
  add("descarga de escarcha",        "frostbolt")
  add("bola de fuego",               "fireball")
  add("bloque de hielo",             "ice block")
  add("polimorfia",                  "polymorph")
  add("oveja",                       "polymorph")
  add("traslación",                  "blink")
  add("cono de frío",                "cone of cold")
  add("joya de escarcha",            "frost nova")
  add("proyectil arcano",            "arcane missiles")
  add("explosión arcana",            "arcane explosion")
  add("contrahechizo",               "counterspell")
  add("combustión",                  "combustion")
  add("presencia mental",            "presence of mind")
  add("ventisca",                    "blizzard")
  add("tormenta de fuego",           "flamestrike")
  add("explosión de fuego",          "fire blast")
  add("espejo de imágenes",          "mirror image")
  add("mesa de banquete",            "conjure table")
  add("conjurar agua",               "conjure water")
  add("conjurar comida",             "conjure food")
  add("portal a ventormenta",        "portal: stormwind")
  add("portal a orgrimmar",          "portal: orgrimmar")
  add("portal a ironforge",          "portal: ironforge")
  add("portal a darnassus",          "portal: darnassus")
  add("portal a entrañas",           "portal: undercity")
  add("portal a thunder bluff",      "portal: thunder bluff")
  add("tele ventormenta",            "teleport: stormwind")
  add("tele orgrimmar",              "teleport: orgrimmar")
  add("romper nieve",                "shatter")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 15: HABILIDADES — BRUJO                 ║
  -- ╚══════════════════════════════════════════════╝
  add("descarga de sombras",         "shadow bolt")
  add("corrupción",                  "corruption")
  add("maldición de agonía",         "curse of agony")
  add("maldición de elementos",      "curse of the elements")
  add("maldición de debilidad",      "curse of weakness")
  add("maldición de agotamiento",    "curse of exhaustion")
  add("lluvia de fuego",             "rain of fire")
  add("tempestad infernal",          "hellfire")
  add("drenar vida",                 "drain life")
  add("drenar alma",                 "drain soul")
  add("drenar maná",                 "drain mana")
  add("destierro",                   "banish")
  add("seducción",                   "seduction")
  add("atar demonio",                "enslave demon")
  add("sacrificio maléfico",         "sacrifice")
  add("maldición de agotamiento",    "curse of exhaustion")
  add("lengua de fuego",             "conflagrate")
  add("tiro de fuego",               "fire bolt")
  add("creación ropas de tela",      "create healthstone")
  add("piedra de salud",             "healthstone")
  add("piedra de alma",              "soulstone")
  add("resurrección del brujo",      "soulstone rez")
  add("soulstone a mi",              "soulstone me")
  add("ponme soulstone",             "soulstone me")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 16: HABILIDADES — CHAMÁN                ║
  -- ╚══════════════════════════════════════════════╝
  add("descarga de relámpagos",      "lightning bolt")
  add("cadena de relámpagos",        "chain lightning")
  add("ansia de sangre",             "bloodlust")
  add("heroísmo",                    "heroism")
  add("furia del viento",            "windfury")
  add("escudo del relámpago",        "lightning shield")
  add("escudo del agua",             "water shield")
  add("curación de cadena",          "chain heal")
  add("marea de oleadas",            "healing wave")
  add("oleada menor",                "lesser healing wave")
  add("golpe de tierra",             "earth shock")
  add("golpe de escarcha",           "frost shock")
  add("golpe de llama",              "flame shock")
  add("ráfaga de viento",            "wind shear")
  add("tótem de terratemblor",       "earthbind totem")
  add("tótem de llama chispa",       "searing totem")
  add("tótem de magma",              "magma totem")
  add("tótem de curación",           "healing stream totem")
  add("tótem de maná primavera",     "mana spring totem")
  add("tótem de gracia del aire",    "grace of air totem")
  add("tótem de fuerza de tierra",   "strength of earth totem")
  add("tótem de resistencia fuego",  "fire resistance totem")
  add("tótem de resistencia naturaleza","nature resistance totem")
  add("tótem de sentido de la tierra","tremor totem")
  add("tótem de intuición",          "stoneclaw totem")
  add("invocar tótem",               "drop totem")
  add("revienta los totems",         "kill the totems")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 17: HABILIDADES — DRUIDA                ║
  -- ╚══════════════════════════════════════════════╝
  add("toque de sanación",           "healing touch")
  add("estimular",                   "innervate")
  add("innervate",                   "estimular")
  add("renacer",                     "rebirth")
  add("resurrección de combate",     "battle rez")
  add("battle res",                  "resurrección de combate")
  add("battle rez",                  "resurrección de combate")
  add("rejuvenecimiento",            "rejuvenation")
  add("floración",                   "lifebloom")
  add("alimentación regenerativa",   "regrowth")
  add("forma de oso",                "bear form")
  add("forma de viaje",              "travel form")
  add("forma de arbol",              "tree form")
  add("forma acuática",              "aquatic form")
  add("forma de gato",               "cat form")
  add("forma de vuelo",              "flight form")
  add("ciclón",                      "cyclone")
  add("enredar",                     "entangling roots")
  add("dormir a la bestia",          "hibernate")
  add("zarpa de la naturaleza",      "nature's grasp")
  add("apuñalar",                    "ravage")
  add("desgarrar",                   "rip")
  add("golpe de raptor",             "rake")
  add("maul",                        "maul")
  add("rugido del oso",              "demoralizing roar")
  add("rugido de guerra",            "war stomp")
  add("luna estelar",                "moonfire")
  add("lluvia estelar",              "starfall")
  add("ira de naturaleza",           "wrath")
  add("tormenta solar",              "solar beam")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 18: ESTADÍSTICAS Y ATRIBUTOS           ║
  -- ╚══════════════════════════════════════════════╝
  add("fuerza",                      "strength")
  add("str",                         "strength")
  add("agilidad",                    "agility")
  add("agi",                         "agility")
  add("intelecto",                   "intellect")
  add("int",                         "intellect")
  add("espíritu",                    "spirit")
  add("spi",                         "spirit")
  add("aguante",                     "stamina")
  add("sta",                         "stamina")
  add("poder de ataque",             "attack power")
  add("poder con hechizos",          "spell power")
  add("poder de hechizos",           "spell power")
  add("daño con hechizos",           "spell damage")
  add("poder de curación",           "healing power")
  add("golpe crítico",               "critical strike")
  add("crítico",                     "crit")
  add("probabilidad de golpe",       "hit chance")
  add("rating de golpe",             "hit rating")
  add("porcentaje de golpe",         "hit percentage")
  add("cap de hit",                  "hit cap")
  add("pericia",                     "expertise")
  add("cap de expertise",            "expertise cap")
  add("esquivar",                    "dodge")
  add("parada",                      "parry")
  add("bloqueo",                     "block")
  add("defensa",                     "defense")
  add("defensa cap",                 "defense cap")
  add("armadura",                    "armor")
  add("penetración arcana",          "spell penetration")
  add("velocidad de lanzamiento",    "casting speed")
  add("velocidad de ataque",         "attack speed")
  add("reducción de armadura",       "armor penetration")
  add("arpen",                       "armor penetration")
  add("resistencia al fuego",        "fire resistance")
  add("resistencia a escarcha",      "frost resistance")
  add("resistencia a naturaleza",    "nature resistance")
  add("resistencia arcana",          "arcane resistance")
  add("resistencia a sombras",       "shadow resistance")
  add("regeneración de vida",        "health regeneration")
  add("regeneración de maná",        "mana regeneration")
  add("mp5",                         "mana per 5 seconds")
  add("maná por 5",                  "mana per 5 seconds")
  add("haste",                       "rapidez")
  add("rapidez",                     "haste")
  add("bonus de sanación",           "healing bonus")
  add("bonificación",                "bonus")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 19: PROFESIONES                         ║
  -- ╚══════════════════════════════════════════════╝
  add("alquimia",                    "alchemy")
  add("herboristería",               "herbalism")
  add("herboristeria",               "herbalism")
  add("minería",                     "mining")
  add("mineria",                     "mining")
  add("herrería",                    "blacksmithing")
  add("herreria",                    "blacksmithing")
  add("ingeniería",                  "engineering")
  add("ingenieria",                  "engineering")
  add("encantamiento",               "enchanting")
  add("peletería",                   "leatherworking")
  add("peleteria",                   "leatherworking")
  add("sastrería",                   "tailoring")
  add("sastreria",                   "tailoring")
  add("cocina",                      "cooking")
  add("pesca",                       "fishing")
  add("primeros auxilios",           "first aid")
  add("recolección",                 "gathering")
  add("crafteo",                     "crafting")
  add("subir profesión",             "level profession")
  add("maxear profesión",            "max profession")
  add("maestro en",                  "master of")
  add("aprender receta",             "learn recipe")
  add("receta de encantamiento",     "enchanting recipe")
  add("receta de alquimia",          "alchemy recipe")
  add("patrón de sastrería",         "tailoring pattern")
  add("diseño de herrería",          "blacksmithing plans")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 20: MATERIALES Y RECURSOS               ║
  -- ╚══════════════════════════════════════════════╝
  -- Telas
  add("paño de lino",                "linen cloth")
  add("paño de lana",                "wool cloth")
  add("paño de seda",                "silk cloth")
  add("paño de tejido de magia",     "mageweave cloth")
  add("paño rúnico",                 "runecloth")
  add("tela de seda",                "silk cloth")
  -- Minerales
  add("mineral de cobre",            "copper ore")
  add("mineral de estaño",           "tin ore")
  add("mineral de hierro",           "iron ore")
  add("mineral de oro",              "gold ore")
  add("mineral de mitril",           "mithril ore")
  add("mineral de torio",            "thorium ore")
  add("barra de cobre",              "copper bar")
  add("barra de bronce",             "bronze bar")
  add("barra de hierro",             "iron bar")
  add("barra de acero",              "steel bar")
  add("barra de mitril",             "mithril bar")
  add("barra de torio",              "thorium bar")
  add("barra de arcanita",           "arcanite bar")
  add("transmutación de arcanita",   "arcanite transmute")
  -- Cueros
  add("cuero ligero",                "light leather")
  add("cuero medio",                 "medium leather")
  add("cuero pesado",                "heavy leather")
  add("cuero grueso",                "thick leather")
  add("cuero basto",                 "rugged leather")
  add("cuero óseo",                  "heavy hide")
  add("escamas de dragón",           "dragonscales")
  add("escamas de dragonkin",        "dragonkin scales")
  add("escamas negras de dragón",    "black dragonscales")
  add("cuero de cocodrilo",          "thick crocodile skin")
  -- Hierbas
  add("raíz de peacebloom",          "peacebloom")
  add("silverleaf",                  "hoja de plata")
  add("earthroot",                   "raíz de tierra")
  add("mageroyal",                   "real del mago")
  add("briarthorn",                  "zarza")
  add("bruiseweed",                  "hierba moreteada")
  add("wild steelbloom",             "flor de acero salvaje")
  add("gromsblood",                  "sangre de grom")
  add("kingsbane",                   "veneno del rey")
  add("arthas lágrimas",             "arthas' tears")
  add("sungrass",                    "hierba solar")
  add("blindweed",                   "hierba ciega")
  add("plaguebloom",                 "flor de la plaga")
  add("mountain silversage",         "salvia de plata de montaña")
  add("icecap",                      "gorrocelo")
  add("dreamfoil",                   "hoja de sueño")
  add("flor de azafrán",             "firebloom")
  add("flor del fuego",              "firebloom")
  -- Gemas y Cristales
  add("cristal de nexo",             "nexus crystal")
  add("esencia astuta",              "lesser eternal essence")
  add("esencia eterna menor",        "lesser eternal essence")
  add("esencia eterna mayor",        "greater eternal essence")
  add("astilla misteriosa menor",    "lesser mystic essence")
  add("polvo de oscuridad",          "dream dust")
  add("polvo de maravilla",          "illusion dust")
  add("esencia la ilusión",          "illusion dust")
  add("fragmento de alma",           "soul shard")
  add("fragmento de sombra",         "shadow shard")
  -- Consumibles de combat
  add("pocion de vida",              "healing potion")
  add("pocion de mana",              "mana potion")
  add("pocion de maná mayor",        "major mana potion")
  add("pocion de vida mayor",        "major healing potion")
  add("pocion de velocidad",         "swiftness potion")
  add("pocion de escarcha",          "frost protection potion")
  add("pocion de fuego",             "fire protection potion")
  add("pocion de naturaleza",        "nature protection potion")
  add("pocion de sombras",           "shadow protection potion")
  add("pocion arcana",               "arcane protection potion")
  add("elixir del gigante",          "elixir of giants")
  add("elixir del mongoose",         "elixir of the mongoose")
  add("elixir de inteligencia",      "elixir of greater intellect")
  add("elixir de la mangosta",       "elixir of the mongoose")
  add("elixir del sabio",            "elixir of greater wisdom")
  add("frasco de supremacía",        "flask of supreme power")
  add("frasco del titán",            "flask of the titans")
  add("frasco de destilación",       "flask of distilled wisdom")
  add("frasco de resistencia",       "flask of chromatic resistance")
  add("comida de buff",              "buff food")
  add("comida con agilidad",         "agility food")
  add("comida con fuerza",           "strength food")
  add("comida con espíritu",         "spirit food")
  add("gamba asada",                 "grilled squid")
  add("pescado asado",               "baked bass")
  add("venda de tejido rúnico",      "runecloth bandage")
  add("venda pesada de rúnico",      "heavy runecloth bandage")
  add("polvo de mana",               "mana dust")
  add("tierra de sombra",            "shadow dust")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 21: PvP Y RANGOS MILITARES              ║
  -- ╚══════════════════════════════════════════════╝
  -- Alianza
  add("soldado raso",                "private")
  add("cabo",                        "corporal")
  add("sargento alianza",            "sergeant")
  add("sargento maestro",            "master sergeant")
  add("sargento mayor alianza",      "sergeant major")
  add("caballero",                   "knight")
  add("caballero teniente",          "knight-lieutenant")
  add("caballero capitán",           "knight-captain")
  add("caballero campeón",           "knight-champion")
  add("teniente comandante",         "lieutenant commander")
  add("comandante",                  "commander")
  add("mariscal",                    "marshal")
  add("mariscal de campo",           "field marshal")
  add("gran mariscal",               "grand marshal")
  -- Horda
  add("zalamero",                    "scout")
  add("grunt",                       "grunt")
  add("guardia de piedra",           "stone guard")
  add("guardia de sangre",           "blood guard")
  add("legionario",                  "legionnaire")
  add("centurión",                   "centurion")
  add("campeón horda",               "champion")
  add("teniente general",            "lieutenant general")
  add("general horda",               "general")
  add("señor de la guerra",          "warlord")
  add("alto señor de la guerra",     "high warlord")
  -- BGs
  add("garganta grito de guerra",    "warsong gulch")
  add("cuenca de arathi",            "arathi basin")
  add("valle de alterac",            "alterac valley")
  add("ojo de la tormenta",          "eye of the storm")
  add("campo de batalla",             "battleground")
  add("cola de campo de batalla",    "battleground queue")
  add("puntos de honor",             "honor points")
  add("puntos de arena",             "arena points")
  add("nuestra bandera",             "our flag")
  add("su bandera",                  "their flag")
  add("capturar bandera",            "cap flag")
  add("la bandera fue tomada",       "flag was taken")
  add("bandera en suelo",            "flag on ground")
  add("bandera devuelta",            "flag returned")
  add("defender base",               "defend base")
  add("capturar base",               "cap base")
  add("establos de arathi",          "stables")
  add("granja de arathi",            "farm")
  add("mina de arathi",              "goldmine")
  add("aserradero de arathi",        "lumber mill")
  add("herrería de arathi",          "blacksmith")
  add("torres de alterac",           "alterac towers")
  add("fuerte norteño",              "stonehearth bunker")
  add("fuerte sureño",               "snowfall graveyard")
  add("fortaleza de drek",           "drek's fortress")
  add("fortaleza de van",            "van's fortress")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 22: GEOGRAFÍA AZEROTH                   ║
  -- ╚══════════════════════════════════════════════╝
  -- Ciudades Alianza
  add("ventormenta",                 "stormwind")
  add("entrada a ventormenta",       "stormwind gate")
  add("ciudad de ventormenta",       "stormwind city")
  add("magos de ventormenta",        "stormwind mages")
  add("forjaz",                      "ironforge")
  add("darnassus",                   "darnassus")
  add("catedral de la luz",          "cathedral of light")
  add("barrio de los magos",         "mage quarter")
  add("el enano borracho",           "the drunken dwarf")
  -- Ciudades Horda
  add("orgrimmar",                   "orgrimmar")
  add("cima del trueno",             "thunder bluff")
  add("entrañas",                    "undercity")
  add("claro de la luna",            "moonglade")
  -- Zonas
  add("bosque de elwynn",            "elwynn forest")
  add("páramos de poniente",         "westfall")
  add("montañas cresta roja",        "redridge mountains")
  add("bosque del ocaso",            "duskwood")
  add("bahía del botín",             "booty bay")
  add("trinquete",                   "ratchet")
  add("ventana de cera",             "wax window")
  add("pantano de las penas",        "swamp of sorrows")
  add("tierras de la peste este",    "eastern plaguelands")
  add("tierras de la peste oeste",   "western plaguelands")
  add("montañas del este",           "eastern kingdoms")
  add("hinterlands",                 "the hinterlands")
  add("tierras altas de arathi",     "arathi highlands")
  add("badlands",                    "badlands")
  add("las tierras bajas",           "the lowlands")
  add("valle de fresno",             "ashenvale")
  add("tierras devastadas",          "blasted lands")
  add("paso de la muerte",           "deadwind pass")
  add("feralas",                     "feralas")
  add("desolace",                    "desolace")
  add("tanaris",                     "tanaris")
  add("silithus",                    "silithus")
  add("tierras de fuego",            "firelands")
  add("llanuras de cenizas",         "ashenvale plains")
  add("cuna del invierno",           "winterspring")
  add("un'goro",                     "un'goro crater")
  add("cazoleta de un'goro",         "un'goro crater")
  add("cordillera de arathi",        "arathi highlands")
  add("zangarmarsh",                 "zangarmarsh")
  add("hellfire peninsula",          "peninsula del fuego infernal")

  -- Puntos de interés
  add("punto de vuelo",              "flight point")
  add("maestra de vuelo",            "flight master")
  add("vuelo al punto",              "take the flight path")
  add("voy en vuelo",                "taking the flight path")
  add("piedra de hogar",             "hearthstone")
  add("tienes hearthstone aquí",     "hearthstoned here?")
  add("ho en ventormenta",           "hearthstone in sw")
  add("ho en org",                   "hearthstone in org")
  add("punto de invocación",         "summoning stone")
  add("cerca de la piedra",          "near the stone")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 23: TURTLE WOW CONTENIDO ESPECÍFICO     ║
  -- ╚══════════════════════════════════════════════╝
  add("carpa de descanso",           "rest tent")
  add("tienda de campaña",           "tent")
  add("carpas",                      "tents")
  add("carpa",                       "tent")
  add("hay carpas aquí",             "any tents here?")
  add("bono de descanso",            "rested xp bonus")
  add("xp de descanso",              "rested xp")
  add("estoy descansado",            "i am rested")
  add("hardcore",                    "hardcore")
  add("modo hardcore",               "hardcore mode")
  add("desafío hardcore",            "hardcore challenge")
  add("murió para siempre",          "died permanently")
  add("perdió su personaje",         "lost their character")
  add("f en el chat",                "press f")
  add("que descanse en paz",         "rip")
  add("ánimo",                       "cheer up")
  add("donado a turtle wow",         "donated to turtle wow")
  add("donación al servidor",        "server donation")
  add("servidor privado",            "private server")
  add("turtle wow",                  "turtle wow")
  add("tierras fantasmas",           "ghostlands")
  add("sueño esmeralda",             "emerald dream")
  add("isla de tel'abim",            "tel'abim isle")
  add("telabim",                     "tel'abim")
  add("hiraeth",                     "hiraeth")
  add("lento y constante",           "slow and steady")
  add("vagabundo en turtle",         "vagrant")
  add("sin usar posada",             "no inns used")
  add("doble especializacion",       "dual spec")
  add("doble spec",                  "dual spec")
  add("spec gratis",                 "free respec")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 24: ADMINISTRACIÓN GUILD Y RAID         ║
  -- ╚══════════════════════════════════════════════╝
  add("hermandad",                   "guild")
  add("maestro de hermandad",        "guild master")
  add("oficial de guild",            "officer")
  add("recluta",                     "recruit")
  add("miembro de guild",            "guild member")
  add("armonización",                "attunement")
  add("attuned",                     "armonizado")
  add("armonizado",                  "attuned")
  add("no armonizado",               "not attuned")
  add("tiene la armonización",       "is attuned")
  add("necesita armonización",       "needs attunement")
  add("durabilidad",                 "durability")
  add("durabilidad baja",            "low durability")
  add("repara equipo",               "repair your gear")
  add("reparar antes del pull",      "repair before the pull")
  add("reparador de combate",        "field repair bot")
  add("robot reparador",             "field repair bot")
  add("mazmorra",                    "dungeon")
  add("mazmorras",                   "dungeons")
  add("raid de 40 personas",         "40 man raid")
  add("raid de 20 personas",         "20 man raid")
  add("raid de 10 personas",         "10 man raid")
  add("listo para la raid",          "raid ready")
  add("raid programada",             "scheduled raid")
  add("hora de raid",                "raid time")
  add("inicio de raid",              "raid start")
  add("hora central europea",        "cet")
  add("hora del servidor",           "server time")
  add("composición de raid",         "raid composition")
  add("composición de grupo",        "group comp")
  add("rostar",                      "roster")
  add("lista de espera",             "waitlist")
  add("en lista de espera",          "on the waitlist")
  add("fuera del rostar",            "not on the roster")
  add("lista de asistencia",         "attendance")
  add("buena asistencia",            "good attendance")
  add("mala asistencia",             "bad attendance")
  add("kickear del grupo",           "kick from group")
  add("loot de consejo",             "loot council")
  add("officer loot",                "officer loot")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 25: MANTENIMIENTO EN RAID Y PARTY       ║
  -- ╚══════════════════════════════════════════════╝
  add("necesito maná",               "low on mana")
  add("necesito mana",               "low on mana")
  add("bebiendo",                    "drinking")
  add("esperen maná",                "waiting for mana")
  add("sin maná",                    "oom")
  add("estoy oom",                   "i am oom")
  add("curame",                      "heal me")
  add("limpiame",                    "cleanse me")
  add("quítame el debuff",           "dispel my debuff")
  add("ponme escudo",                "shield me")
  add("invócame por favor",          "summon me plz")
  add("dame agua del mago",          "give me mage water")
  add("dame comida del mago",        "give me mage food")
  add("usa la piedra de hogar",      "hearthstone")
  add("piedra de invocación lista",  "summoning stone is up")
  add("están todos en la piedra",    "everyone at the stone")
  add("necesito invocación",         "i need a summon")
  add("invócame a la mazmorra",      "summon me to the dungeon")
  add("listo para el pull",          "ready to pull")
  add("empezamos cuando quieran",    "ready when you are")
  add("hacemos el pull en",          "pulling in")
  add("pullcando",                   "pulling")
  add("preparados para el pull",     "ready for pull")
  add("pull fallido",                "bad pull")
  add("se me fue el pull",           "lost the pull")
  add("aggro al healer",             "healer has aggro")
  add("el healer está muriendo",     "healer is dying")
  add("necesito rez",                "need a rez")
  add("néceito resurección",         "need a resurrection")
  add("me puedes rezar",             "can you rez me")
  add("dame rez",                    "rez me")
  add("reu en la piedra",            "regroup at stone")
  add("vayan a reparar",             "go repair")
  add("queda poco tiempo",           "running out of time")
  add("nos hemos quedado sin tiempo","out of time")
  add("empezamos otra vez",          "starting again")
  add("siguiente pull",              "next pull")
  add("boss directo",                "straight to the boss")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 26: SLOTS DE EQUIPO Y OBJETOS           ║
  -- ╚══════════════════════════════════════════════╝
  add("cabeza",                      "head")
  add("cuello",                      "neck")
  add("espalda",                     "back")
  add("capa",                        "cloak")
  add("pecho",                       "chest")
  add("muñecas",                     "wrists")
  add("brazales",                    "bracers")
  add("manos",                       "hands")
  add("guantes",                     "gloves")
  add("cinturón",                    "belt")
  add("piernas",                     "legs")
  add("pantalones",                  "pants")
  add("pies",                        "feet")
  add("botas",                       "boots")
  add("dedo",                        "finger")
  add("anillo",                      "ring")
  add("amuleto",                     "trinket")
  add("reliquia",                    "relic")
  add("off-hand",                    "off hand weapon")
  add("mano secundaria",             "off hand")
  add("arma principal",              "main hand")
  add("arma a dos manos",            "two-handed weapon")
  add("arco",                        "bow")
  add("ballesta",                    "crossbow")
  add("vara",                        "wand")
  add("espada",                      "sword")
  add("hacha",                       "axe")
  add("maza",                        "mace")
  add("bastón de magia",             "staff")
  add("daga",                        "dagger")
  add("lanza",                       "polearm")
  add("fist weapon",                 "arma de puño")
  add("arma de puño",                "fist weapon")
  add("escudo",                      "shield")
  add("t1",                          "tier 1")
  add("t2",                          "tier 2")
  add("t3",                          "tier 3")
  add("set de tier uno",             "tier 1 set")
  add("set de tier dos",             "tier 2 set")
  add("set de tier tres",            "tier 3 set")
  add("pieza de set",                "set piece")
  add("bono de set",                 "set bonus")
  add("objeto épico",                "epic item")
  add("objeto raro",                 "rare item")
  add("objeto poco común",           "uncommon item")
  add("objeto legendario",           "legendary item")
  add("purple",                      "épico")
  add("naranja",                     "legendary")
  add("azul",                        "rare")
  add("verde",                       "uncommon")
  add("gris",                        "poor")
  add("blanco loot",                 "common loot")
  add("pre-bis",                     "pre best in slot")
  add("bis",                         "best in slot")
  add("mejor pieza posible",         "best in slot")
  add("mejora",                      "upgrade")
  add("no es mejora para mí",        "not an upgrade for me")
  add("es mejora para mí",           "it's an upgrade for me")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 27: MISIONES Y PROGRESIÓN               ║
  -- ╚══════════════════════════════════════════════╝
  add("misión",                      "quest")
  add("misiones",                    "quests")
  add("registro de misiones",        "quest log")
  add("completar misión",            "complete quest")
  add("entregar misión",             "turn in quest")
  add("recompensa de misión",        "quest reward")
  add("misión de cadena",            "chain quest")
  add("misión de raid",              "raid quest")
  add("misión de élite",             "elite quest")
  add("misión diaria",               "daily quest")
  add("misión semanal",              "weekly quest")
  add("reputación",                  "reputation")
  add("rep",                         "reputation")
  add("neutral",                     "neutral")
  add("amistoso",                    "friendly")
  add("honorable",                   "honored")
  add("reverenciado",                "revered")
  add("exaltado",                    "exalted")
  add("odiado",                      "hated")
  add("hostil",                      "hostile")
  add("grindear reputación",         "grind reputation")
  add("grindear rep",                "rep grind")
  add("experiencia",                 "experience")
  add("xp",                          "experience")
  add("nivel",                       "level")
  add("subir nivel",                 "level up")
  add("dinged",                      "subí de nivel")
  add("ding",                        "subí de nivel")
  add("bienvenido al nivel 60",      "welcome to level 60")
  add("llegar al máximo",            "hit max level")
  add("nivel máximo",                "max level")
  add("al 60",                       "at level 60")
  add("montura",                     "mount")
  add("75 de montura",               "60 percent mount")
  add("100 de montura",              "100 percent mount")
  add("montura épica",               "epic mount")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 28: ETIQUETA SOCIAL Y CLIMA             ║
  -- ╚══════════════════════════════════════════════╝
  add("muchas gracias por el grupo", "tyvm for the group")
  add("buena suerte con los drops",  "gl with drops")
  add("felicidades por el nivel",    "gz on the level")
  add("felicidades por el logro",    "gz on the achievement")
  add("felicidades",                 "grats")
  add("que tengas un buen dia",      "have a nice day")
  add("que pases una buena noche",   "have a good night")
  add("que descanses",               "get some rest")
  add("cuídate",                     "take care")
  add("saludos",                     "greetings")
  add("saludos a todos",             "greetings everyone")
  add("nos vemos en el juego",       "see you in game")
  add("hasta pronto",                "see you soon")
  add("mañana jugamos",              "let's play tomorrow")
  add("fue divertido",               "that was fun")
  add("mal día para jugar",          "bad day to play")
  add("estoy tilteado",              "i'm tilted")
  add("me toca descansar",           "gotta take a break")
  add("gracias por la raid",         "thanks for the raid")
  add("buen pull",                   "nice pull")
  add("buen intento",                "good attempt")
  add("casi lo logramos",            "so close")
  add("la próxima vez",              "next time")
  add("el destino nos tiene en mente","destiny has us in mind")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 29: EMOTES Y EXPRESIONES               ║
  -- ╚══════════════════════════════════════════════╝
  add("jajaja",                      "lol")
  add("muerto de risa",              "lmao")
  add("que gracioso",                "so funny")
  add("me haces reír",               "you make me laugh")
  add("no puede ser",                "no way")
  add("impresionante",               "impressive")
  add("increíble",                   "incredible")
  add("brutal",                      "sick")
  add("dios mío",                    "oh my god")
  add("ay no",                       "oh no")
  add("qué lastima",                 "that's a shame")
  add("qué pena",                    "what a shame")
  add("buenísimo",                   "awesome")
  add("genial",                      "great")
  add("extraordinario",              "extraordinary")
  add("clásico",                     "classic")
  add("qué momento",                 "what a moment")
  add("eso duele",                   "that hurts")
  add("nooo",                        "noooo")
  add("siii",                        "yesss")
  add("eso estuvo bien",             "that was nice")
  add("mal jugado",                  "bad play")
  add("bien jugado",                 "well played")
  add("nunca me canso de esto",      "never get tired of this")
  add("primera vez",                 "first time")
  add("nunca lo había visto",        "never seen this before")
  add("qué suerte",                  "so lucky")
  add("qué mala suerte",             "so unlucky")
  add("drop increíble",              "amazing drop")
  add("no cayó nada",                "nothing dropped")
  add("maldito rng",                 "damn rng")
  add("el rng no me quiere",         "rng hates me")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 30: MECÁNICAS DE JUEGO Y UI             ║
  -- ╚══════════════════════════════════════════════╝
  add("addon",                       "addon")
  add("interfaz de usuario",         "user interface")
  add("lag",                         "lag")
  add("latencia",                    "latency")
  add("ping",                        "ping")
  add("desconectado",                "disconnected")
  add("dc",                          "disconnected")
  add("se desconectó",               "got disconnected")
  add("crasheó el juego",            "game crashed")
  add("bajo fps",                    "low fps")
  add("estoy congelado",             "i'm frozen")
  add("me lageo",                    "i'm lagging")
  add("bug del juego",               "game bug")
  add("error del servidor",          "server error")
  add("caída del servidor",          "server crash")
  add("mantenimiento del servidor",  "server maintenance")
  add("reinicio del servidor",       "server restart")
  add("reportar un bug",             "report a bug")
  add("barra de acción",             "action bar")
  add("barra de salud",              "health bar")
  add("barra de maná",               "mana bar")
  add("barra de energía",            "energy bar")
  add("barra de rabia",              "rage bar")
  add("marcos de unidad",            "unit frames")
  add("marco del jugador",           "player frame")
  add("marco del objetivo",          "target frame")
  add("mapa del mundo",              "world map")
  add("minimapa",                    "minimap")
  add("hoja de personaje",           "character sheet")
  add("árbol de talentos",           "talent tree")
  add("talentos",                    "talents")
  add("respeccear",                  "respec")
  add("resetear talentos",           "reset talents")
  add("libro de hechizos",           "spellbook")
  add("habilidades",                 "abilities")
  add("bolsa",                       "bag")
  add("mochila",                     "backpack")
  add("inventario lleno",            "bags are full")
  add("bolsas llenas",               "bags are full")
  add("necesito bolsas más grandes", "need bigger bags")
  add("vendor",                      "vendedor")
  add("vendedor",                    "vendor")
  add("comprar materiales",          "buy mats")
  add("vender basura",               "sell junk")
  add("vender todo gris",            "sell all grey")
  add("reparar equipo",              "repair gear")
  add("macros",                      "macros")
  add("configuracion del juego",     "game settings")
  add("volumen de música",           "music volume")
  add("volumen de efectos",          "sfx volume")
  add("captura de pantalla",         "screenshot")
  add("sacar foto",                  "take screenshot")

  -- ╔══════════════════════════════════════════════╗
  -- ║  CAT 31: NÚMEROS Y CANTIDADES                ║
  -- ╚══════════════════════════════════════════════╝
  add("uno más",                     "1 more")
  add("dos más",                     "2 more")
  add("tres más",                    "3 more")
  add("cuatro más",                  "4 more")
  add("cinco más",                   "5 more")
  add("primer intento",              "first attempt")
  add("segundo intento",             "second attempt")
  add("estamos en progresión",       "we are progressing")
  add("primer kill",                 "first kill")
  add("nuevo récord",                "new record")
  add("record del servidor",         "server record")
  add("record de guild",             "guild record")
  add("cien mil de oro",             "100k gold")
  add("mil de oro",                  "1k gold")
  add("cien de oro",                 "100 gold")
  add("cuánto oro",                  "how much gold")
  add("oro de la semana",            "weekly gold")
  add("costos de reparación",        "repair costs")

  -- ╔════════════════════════════════════════════════════════════════╗
  -- ║  CAT 32: VOCABULARIO ESPECÍFICO CHINO (TRILINGÜE OMNI-TIER)    ║
  -- ╚════════════════════════════════════════════════════════════════╝
  add("afk", "fuera del teclado", "离开")
  add("brb", "vuelvo enseguida", "马上回来")
  add("omw", "en camino", "在路上")
  add("lfg", "busco grupo", "寻找队伍")
  add("lfm", "busco mas", "寻找更多人")
  add("inv", "invitame", "求组")
  add("tanque", "tank", "坦克")
  add("sanador", "healer", "治疗")
  add("dps", "dps", "输出")
  add("guerrero", "warrior", "战士")
  add("mago", "mage", "法师")
  add("sacerdote", "priest", "牧师")
  add("pícaro", "rogue", "盗贼")
  add("brujo", "warlock", "术士")
  add("cazador", "hunter", "猎人")
  add("paladín", "paladin", "圣骑士")
  add("chamán", "shaman", "萨满")
  add("druida", "druid", "德鲁伊")
  add("minas de la muerte", "deadmines", "死亡矿井")
  add("cavernas de los lamentos", "wailing caverns", "哀嚎洞穴")
  add("monasterio escarlata", "scarlet monastery", "血色修道院")
  add("profundidades de rocanegra", "blackrock depths", "黑石深渊")
  add("brd", "profundidades de rocanegra", "黑石深渊")
  add("núcleo de magma", "molten core", "熔火之心")
  add("guarida alanegra", "blackwing lair", "黑翼之巢")
  add("guarida de onyxia", "onyxia's lair", "奥妮克希亚的巢穴")
  add("naxxramas", "naxxramas", "纳克萨玛斯")
  add("vendo", "wts", "出售")
  add("compro", "wtb", "求购")
  add("cambio", "wtt", "交换")
  add("oro", "gold", "金币")
  add("subasta", "ah", "拍卖行")
  add("ventormenta", "stormwind", "暴风城")
  add("forjaz", "ironforge", "铁炉堡")
  add("orgrimmar", "orgrimmar", "奥格瑞玛")
  add("cima del trueno", "thunder bluff", "雷霆崖")
  add("entrañas", "undercity", "幽暗城")
  add("darnassus", "darnassus", "达纳苏斯")
  add("ayuda", "help", "救命")
  add("hola", "hello", "你好")
  add("gracias", "thanks", "谢谢")
  add("de nada", "you are welcome", "不客气")
  add("si", "yes", "是")
  add("no", "no", "否")
  add("vamos", "let's go", "出发")
  add("cuidado", "watch out", "小心")
  add("mana", "mana", "没蓝")
  add("buff", "buff", "加buff")
  add("res", "resurrection", "复活")
  add("portal", "portal", "开门")
  add("agua", "water", "做水")
  add("comida", "food", "面包")
  add("piedra de hogar", "hearthstone", "炉石")
  add("necesito", "need", "需要")
  add("vengan", "come", "来")
  add("hacer mazmorra", "do dungeon", "打本")

  -- ╔══════════════════════════════════════════════╗
  -- ║  LÓGICA DE ORDENAMIENTO (Greedy Matching)    ║
  -- ╚══════════════════════════════════════════════╝
  local p_keys = { "es_en", "en_es", "zh_en", "en_zh", "zh_es", "es_zh" }
  for _, p in ipairs(p_keys) do
    table.sort(pfUI.translator_dicts[p .. "_keys"], function(a, b) return strlen(a) > strlen(b) end)
  end

  if pfUI_config.translator and pfUI_config.translator.debug_mode == "1" then
    DEFAULT_CHAT_FRAME:AddMessage("|cff33ffcc[TR]|r Lexicon v6.0 Omni-Tier Trilingüe cargado.")
  end
end)
