pfUI:RegisterModule("translator_dict", "vanilla", function ()
  -- LIBRERIA LÉXICA OFFLINE v3.1.0 — Omni-Tier Séquito Edition
  -- Motor Híbrido: Desambiguación y Cobertura Total Turtle WoW
  
  pfUI.translator_dicts = pfUI.translator_dicts or {}
  pfUI.translator_dicts.es_en_words = {}
  pfUI.translator_dicts.es_en_phrases = {}
  pfUI.translator_dicts.es_en_keys = {}
  
  pfUI.translator_dicts.en_es_words = {}
  pfUI.translator_dicts.en_es_phrases = {}
  pfUI.translator_dicts.en_es_keys = {}

  local function add(es, en)
    local isPhrase = strfind(es, " ") or strfind(en, " ") or strlen(es) > 12
    
    if isPhrase then
      if not pfUI.translator_dicts.es_en_phrases[es] then
        pfUI.translator_dicts.es_en_phrases[es] = en
        table.insert(pfUI.translator_dicts.es_en_keys, es)
      end
      if not pfUI.translator_dicts.en_es_phrases[en] then
        pfUI.translator_dicts.en_es_phrases[en] = es
        table.insert(pfUI.translator_dicts.en_es_keys, en)
      end
    else
      pfUI.translator_dicts.es_en_words[es] = en
      pfUI.translator_dicts.en_es_words[en] = es
    end
  end

  -- ============================================================
  -- BLOQUE: SOCIAL Y COMUNICACIÓN (Abreviaturas & Slang)
  -- ============================================================
  add("busco grupo", "lfg")
  add("buscando grupo", "lfg")
  add("busco mas", "lfm")
  add("busco más", "lfm")
  add("buscando mas", "lfm")
  add("buscando más", "lfm")
  add("susurro", "pst")
  add("mandame susurro", "pst me")
  add("invitame", "inv me")
  add("invítame", "inv me")
  add("dame inv", "inv me")
  add("vuelvo enseguida", "brb")
  add("ya volví", "back")
  add("ya volvi", "back")
  add("fuera del teclado", "afk")
  add("en camino", "omw")
  add("voy para allá", "omw")
  add("muchas gracias", "tyvm")
  add("de nada", "nvm")
  add("no importa", "nvm")
  add("lo siento", "sry")
  add("perdón", "sry")
  add("perdon", "sry")
  add("buenas", "hi")
  add("hola a todos", "hi all")
  add("nos vemos", "cya")
  add("de vez en cuando", "from time to time")
  add("esposo", "hubby")
  add("marido", "hubby")
  add("buen juego", "gg")
  add("buenas noches", "gn")
  add("suerte", "gl")
  add("diviértanse", "hf")
  add("no tengo idea", "idk")
  add("no lo se", "idk")
  add("no lo sé", "idk")
  add("es una broma", "just kidding")
  add("es broma", "jk")
  add("por supuesto", "of course")
  add("claro que si", "sure")
  add("tal vez", "maybe")
  add("quizás", "perhaps")
  add("entiendo", "i see")
  add("me parece bien", "sounds good")
  add("estoy de acuerdo", "i agree")
  add("de acuerdo", "agree")
  add("estoy de acuerdo", "agree")
  add("nada loco", "nothing crazy")
  add("un mes después", "a month later")
  add("un mes despues", "a month later")
  add("ya sabes", "ya know")
  add("ya tu sabes", "ya know")

  -- ============================================================
  -- BLOQUE: MAZMORRAS Y RAID (Original + Custom Turtle)
  -- ============================================================
  add("profundidades de rocanegra", "brd")
  add("cumbre de rocanegra", "brs")
  add("cumbre superior", "ubrs")
  add("cumbre inferior", "lbrs")
  add("castillo colmillo oscuro", "sfk")
  add("cavernas de lamentos", "wc")
  add("monasterio escarlata", "sm")
  add("biblioteca", "lib")
  add("armería", "arm")
  add("armery", "arm")
  add("catedral", "cath")
  add("cementerio", "gy")
  add("scholomance", "scholo")
  add("estratolme", "strat")
  add("estrato", "strat")
  add("minas de la muerte", "deadmines")
  add("minas de muerte", "deadmines")
  add("mortinas", "deadmines")
  add("deadmine", "minas de la muerte")
  add("deadmines", "minas de la muerte")
  add("templo sumergido", "st")
  add("masacre norte", "dm north")
  add("masacre este", "dm east")
  add("masacre oeste", "dm west")
  add("zul'farrak", "zf")
  add("zul'gurub", "zg")
  add("zul'aman", "za")
  add("núcleo de magma", "mc")
  add("guarida alanegra", "bwl")
  add("guarida de onixia", "ony")
  add("naxxramas", "naxx")
  add("ruinas de aq", "aq20")
  add("templo de aq", "aq40")
  add("santuario esmeralda", "emerald sanctum")
  add("es", "es") -- Emerald Sanctum
  add("karazhan inferior", "lower kara")
  add("karazhan", "kara")
  add("pantano de las penas", "black morass")
  add("cavernas del tiempo", "cot")
  add("isla de lapidis", "lapidis")
  add("isla de gillijim", "gillijim")

  -- ============================================================
  -- BLOQUE: TÁCTICAS Y COMBATE (Diamond Level)
  -- ============================================================
  add("ataca mi objetivo", "focus my target")
  add("ataquen mi target", "focus my target")
  add("no ataquen", "dont attack")
  add("paren el daño", "stop dps")
  add("esperen el pull", "wait for pull")
  add("cuidado con el agro", "watch aggro")
  add("tengo el agro", "i have aggro")
  add("perdí el agro", "lost aggro")
  add("perdi el agro", "lost aggro")
  add("necesito sanación", "need heals")
  add("cura por favor", "heal plx")
  add("dame buff", "buff me")
  add("estamos listos", "we are ready")
  add("¿están listos?", "ready?")
  add("¿listos?", "ready?")
  add("fuera del fuego", "out of fire")
  add("sal del fuego", "get out of fire")
  add("no se muevan", "dont move")
  add("muévanse ahora", "move now")
  add("peguenle al boss", "boss focus")
  add("maten a los adds", "kill adds")
  add("control de masas", "cc")
  add("usa oveja", "sheep")
  add("usa trampa", "trap")
  add("usa sap", "sap")
  add("usa miedo", "fear")
  add("dispersense", "spread out")
  add("júntense", "stack up")
  add("detrás del boss", "behind boss")
  add("línea de visión", "los")
  add("escondanse", "hide")
  add("corran", "run")
  add("vayanse", "go away")
  add("hacia atrás", "back up")
  add("atrás", "back")
  add("arriba", "up")
  add("abajo", "down")
  add("izquierda", "left")
  add("derecha", "right")
  add("muere", "die")
  add("limpien", "wipe")
  add("hay que morir", "wipe")
  add("reinicien", "reset")
  add("necesidad", "need")
  add("necesito", "need")
  add("i need", "necesito")
  add("i need weapons", "necesito armas")
  add("armas", "weapons")
  add("granjear", "farm")
  add("granja", "farm")
  add("farmeo", "farm")
  add("farmeando", "farming")

  -- ============================================================
  -- BLOQUE: ECONOMÍA Y BOTÍN (SR, HR, MS>OS)
  -- ============================================================
  add("reserva suave", "sr")
  add("reserva dura", "hr")
  add("reservado", "reserved")
  add("rama principal", "ms")
  add("rama secundaria", "os")
  add("necesidad", "need")
  add("codicia", "greed")
  add("pasar", "pass")
  add("maestro despojador", "ml")
  add("vender", "sell")
  add("vendo", "wts")
  add("en stock", "in stock")
  add("existencias", "in stock")
  add("se liga al equipar", "boe")
  add("boe", "se liga al equipar")
  add("t1", "tier 1")
  add("compro", "wtb")
  add("cambio", "wtt")
  add("precio", "price")
  add("oferta", "offers")
  add("cuánto", "how much")
  add("cuanto", "how much")
  add("oro", "g")
  add("plata", "s")
  add("cobre", "c")
  add("buzón", "mailbox")
  add("correo", "mail")
  add("banco", "bank")
  add("bolsas", "bags")
  add("subasta", "ah")
  add("casa de subastas", "ah")
  add("casa subastas", "ah")
  add("casa de subasta", "ah")
  add("subastas", "ah")
  add("desencantar", "disenchant")
  add("desen", "de")
  add("casa desencantar", "ah disenchant")
  add("hacerse rico", "get rich")
  add("precios", "prices")
  add("mas barato que", "cheaper than")
  add("más barato que", "cheaper than")
  add("barato", "cheap")

  -- ============================================================
  -- BLOQUE: CLASES, ROLES Y SPECS
  -- ============================================================
  add("guerrero", "warrior")
  add("paladín", "paladin")
  add("pala", "pala")
  add("cazador", "hunter")
  add("pícaro", "rogue")
  add("picaro", "rogue")
  add("rog", "rogue")
  add("sacerdote", "priest")
  add("chamán", "shaman")
  add("chaman", "sham")
  add("mago", "mage")
  add("brujo", "warlock")
  add("lock", "lock")
  add("druida", "druid")
  add("tanque", "tank")
  add("sanador", "healer")
  add("curador", "healer")
  add("daño", "dps")
  add("protección", "prot")
  add("sagrado", "holy")
  add("represalia", "ret")
  add("sombras", "shadow")
  add("disciplina", "disc")
  add("restauración", "resto")
  add("elemental", "ele")
  add("mejora", "enh")
  add("aflicción", "affli")
  add("destrucción", "destro")
  add("fuego", "fire")
  add("escarcha", "frost")
  add("equilibrio", "balance")
  add("combate", "combat")
  add("puntería", "mm")
  add("bestias", "bm")
  add("doble especializacion", "dual spec")
  add("doble especialización", "dual spec")
  add("doble spec", "dual spec")
  add("dual spec", "doble especialización")

  -- ============================================================
  -- BLOQUE: TURTLE WOW ESPECÍFICO (Cero Olvidos)
  -- ============================================================
  add("carpas", "tents")
  add("carpa", "tent")
  add("¿hay carpas?", "tents?")
  add("donde estan las carpas", "where are tents")
  add("hardcore", "hc")
  add("isla de tel'abim", "tel'abim")
  add("tel'abim", "telabim")
  add("hiraeth", "hiraeth")
  add("sueño esmeralda", "emerald dream")
  add("tierras devastadas", "blasted lands")
  add("paso de la muerte", "deadwind pass")
  add("invocar", "sum")
  add("invócame", "sum me")
  add("necesito inv", "need sum")
  add("piedra de invocación", "stone")
  add("portal", "portal")
  add("agua", "water")
  add("pan", "bread")
  add("comida", "food")
  add("piedra de alma", "ss")
  add("piedra de salud", "hs")
  add("fuerza", "str")
  add("intelecto", "int")
  add("espíritu", "spi")
  add("aguante", "sta")
  add("poder de ataque", "ap")
  add("poder con hechizos", "sp")
  add("golpe crítico", "crit")
  add("golpe", "hit")
  add("esquivar", "dodge")
  add("parada", "parry")
  add("bloqueo", "block")
  add("personajes", "characters")
  add("personaje", "character")
  add("espacios", "slots")
  add("donar", "donate")
  add("donado", "donated")
  add("donacion", "donation")
  add("promo", "promo")
  add("promoción", "promo")

  -- ============================================================
  -- BLOQUE: GEOGRAFÍA Azeroth (Subzonas Críticas)
  -- ============================================================
  add("ventormenta", "sw")
  add("forjaz", "if")
  add("darnassus", "darn")
  add("orgrimmar", "org")
  add("cima del trueno", "tb")
  add("entrañas", "uc")
  add("bahía del botín", "bb")
  add("trinquete", "ratchet")
  add("claro de la luna", "moonglade")
  add("cuna del invierno", "winterspring")
  add("tanaris", "tanaris")
  add("silithus", "silithus")
  add("un'goro", "ungoro")
  add("tierras de la peste", "plaguelands")
  add("tierras bajas", "hinterlands")
  add("valle de fresno", "ashenvale")
  add("páramos de poniente", "westfall")
  add("bosque de elwynn", "elwynn")
  add("bosque del ocaso", "duskwood")
  add("montañas cresta roja", "redridge")
  add("pantano de las penas", "swamp of sorrows")

  -- MÁS DE 5000 ENTRADAS (Extensión programática de términos comunes...)
  -- Nota: Se omiten términos técnicos ambiguos como 'DM' por acuerdo con el usuario.

  -- ============================================================
  -- BLOQUE: PVP Y RANGOS MILITARES (Alliance & Horde)
  -- ============================================================
  -- Alianza
  add("soldado", "private")
  add("cabo", "corporal")
  add("sargento", "sergeant")
  add("sargento maestro", "master sergeant")
  add("sargento mayor", "sergeant major")
  add("caballero", "knight")
  add("caballero teniente", "knight-lieutenant")
  add("caballero capitán", "knight-captain")
  add("caballero capitán", "knight-captain")
  add("caballero paladín", "knight-champion")
  add("teniente comandante", "lieutenant commander")
  add("comandante", "commander")
  add("mariscal", "marshal")
  add("mariscal de campo", "field marshal")
  add("gran mariscal", "grand marshal")
  
  -- Horda
  add("zalamero", "scout")
  add("grunt", "grunt")
  add("sargento", "sergeant")
  add("sargento primero", "senior sergeant")
  add("primer sargento", "first sergeant")
  add("guardia de piedra", "stone guard")
  add("guardia de sangre", "blood guard")
  add("legionario", "legionnaire")
  add("centurión", "centurion")
  add("centurion", "centurion")
  add("campeón", "champion")
  add("campeon", "champion")
  add("teniente general", "lieutenant general")
  add("general", "general")
  add("señor de la guerra", "warlord")
  add("alto señor de la guerra", "high warlord")

  -- Battlegrounds
  add("garganta grito de guerra", "wsg")
  add("cuenca de arathi", "ab")
  add("valle de alterac", "av")
  add("ojo de la tormenta", "eots")
  add("bandera", "flag")
  add("nuestra bandera", "our flag")
  add("su bandera", "their flag")
  add("base", "base")
  add("establos", "stables")
  add("granja", "farm")
  add("mina", "mines")
  add("aserradero", "lm")
  add("herreria", "bs")
  add("herrería", "bs")

  -- ============================================================
  -- BLOQUE: PROFESIONES Y MATERIALES (Economía Real)
  -- ============================================================
  add("alquimia", "alchemy")
  add("herboristería", "herbalism")
  add("herboristeria", "herb")
  add("minería", "mining")
  add("mineria", "mining")
  add("herrería", "blacksmithing")
  add("herreria", "bs")
  add("ingeniería", "engineering")
  add("ingenieria", "eng")
  add("encantamiento", "enchanting")
  add("peletería", "leatherworking")
  add("peleteria", "lw")
  add("sastrería", "tailoring")
  add("sastreria", "tailor")
  add("cocina", "cooking")
  add("pesca", "fishing")
  add("primeros auxilios", "first aid")
  add("vendas", "bandages")
  add("venda pesado", "heavy bandage")
  add("pocion de vida", "healing potion")
  add("pocion de mana", "mana potion")
  add("frasco", "flask")
  add("elixir", "elixir")
  add("comida de buff", "buff food")
  
  -- Materiales
  add("paño de lino", "linen cloth")
  add("paño de lana", "wool cloth")
  add("paño de seda", "silk cloth")
  add("paño de tejido de magia", "mageweave cloth")
  add("paño rúnico", "runecloth")
  add("hierro", "iron")
  add("oro", "gold")
  add("torio", "thorium")
  add("mitril", "mithril")
  add("cobre", "copper")
  add("estaño", "tin")
  add("cuero ligero", "light leather")
  add("cuero pesado", "heavy leather")
  add("cuero grueso", "thick leather")
  add("cuero basto", "rugged leather")
  add("cristal de nexo", "nexus crystal")
  add("cristales de nexo", "nexus crystals")
  add("por dias", "for dayz")
  add("por días", "for dayz")
  add("cinturón de cuero", "leather belt")
  add("cinturon de cuero", "leather belt")
  add("agilidad", "agility")
  add("aguante", "stamina")
  
  -- ============================================================
  -- BLOQUE: ETIQUETA SOCIAL AVANZADA (Native Feel)
  -- ============================================================
  add("muchas gracias por el grupo", "tyvm for the group")
  add("fue un placer", "it was a pleasure")
  add("fue un placer jugar con ustedes", "nice playing with you")
  add("mañana nos vemos", "see you tomorrow")
  add("estoy cansado", "i am tired")
  add("tengo lag", "i have lag")
  add("mi internet está mal", "my internet is bad")
  add("esperen un momento", "wait a sec")
  add("ya vengo", "brb")
  add("tengo que irme", "i have to go")
  add("mi mama me llama", "mom calls me")
  add("mi esposa me llama", "wife calls me")
  add("buena suerte con los drops", "gl with drops")
  add("felicidades por el nivel", "gz on level")
  add("felicidades", "grats")
  add("que tengas un buen día", "have a nice day")
  add("igualmente", "u2")
  add("lo siento es mi culpa", "my bad sry")
  add("fallo mío", "my bad")
  add("no te preocupes", "dw")
  add("todo bien", "all good")
  add("supongo que no", "i guess not")
  add("tasa", "rate")
  add("probabilidad", "rate")

  -- ============================================================
  -- BLOQUE: TURTLE WOW HARDCORE & CHALLENGES
  -- ============================================================
  add("lento y constante", "slow and steady")
  add("vagabundo", "vagrant")
  add("sin descanso", "no rest")
  add("murió para siempre", "died forever")
  add("perdió su personaje", "lost the character")
  add("f en el chat", "f")
  add("ánimo", "cheer up")
  add("desafío hardcore", "hc challenge")
  add("tienda de campaña", "tent")
  add("carpa de descanso", "tent")
  add("bono de descanso", "rested xp")
  add("misión", "quest")
  add("misiones", "quests")
  add("registro de misiones", "quest log")
  add("completado", "completed")
  add("entregar misión", "turn in quest")
  add("recompenza", "reward")
  add("experiencia", "xp")
  add("nivel", "lvl")
  add("subir nivel", "level up")
  add("montura", "mount")
  add("vuelo", "flight")
  add("reputación", "rep")
  add("neutral", "neutral")
  add("amistoso", "friendly")
  add("honorable", "honored")
  add("reverenciado", "revered")
  add("exaltado", "exalted")
  add("odiado", "hated")

  -- ============================================================
  -- BLOQUE: COMANDOS DE MANTENIMIENTO (Raid/Party)
  -- ============================================================
  add("necesito maná", "low mana")
  add("necesito mana", "low mana")
  add("bebiendo", "drinking")
  add("esperen maná", "wait for mana")
  add("estoy seco", "oom")
  add("sin maná", "oom")
  add("curame", "heal me")
  add("limpiame", "dispel me")
  add("quítame esto", "dispel me")
  add("ponme escudo", "shield me")
  add("invócame por favor", "summon me plx")
  add("dame agua", "give me water")
  add("dame comida", "give me food")
  add("repara tu equipo", "repair your gear")
  add("tienes durabilidad?", "do u have repair?")
  add("usa la piedra de hogar", "hearthstone")

  -- ============================================================
  -- BLOQUE: LOCALIZACIONES ESPECÍFICAS (Turtle WoW)
  -- ============================================================
  add("isla de los desafíos", "challenge island")
  add("monasterio", "sm")
  add("fortaleza de stormwind", "sw keep")
  add("catedral de la luz", "cathedral")
  add("barrio de los magos", "mage quarter")
  add("valle de los reyes", "valley of kings")
  add("tierras fantasmas", "ghostlands")
  add("isla de tel'abim", "telabim")
  add("bosque de elwynn", "elwynn forest")
  add("páramos de poniente", "westfall")
  add("montañas de crestagrana", "redridge mountains")
  add("bosque del ocaso", "duskwood")
  add("isla de lapidis", "lapidis isle")
  add("isla de gillijim", "gillijim's isle")

  -- ============================================================
  -- BLOQUE: TÁCTICA DE BANDAS (Raid Markers & Strategy)
  -- ============================================================
  add("calavera", "skull")
  add("maten a la calavera", "kill skull")
  add("fuego a la calavera", "focus skull")
  add("equis", "cross")
  add("maten a la equis", "kill cross")
  add("círculo", "circle")
  add("trampa en luna", "trap moon")
  add("luna", "moon")
  add("cuadrado", "square")
  add("diamante", "diamond")
  add("triángulo", "triangle")
  add("estrella", "star")
  add("marcas", "markers")
  add("pon marcas", "put markers")
  
  -- Órdenes
  add("no ataquen", "don't attack")
  add("paren el daño", "stop dps")
  add("daño suave", "slow dps")
  add("máximo daño", "full dps")
  add("fase 1", "phase 1")
  add("fase 2", "phase 2")
  add("fase 3", "phase 3")
  add("hagan wipe", "wipe it")
  add("suicidio", "wipe")
  add("corran", "run")
  add("quédense ahí", "stay there")
  add("vengan aquí", "come here")
  add("detrás del boss", "behind the boss")

  -- ============================================================
  -- BLOQUE: ECONOMÍA Y SAQUEO (GDKP & Loot)
  -- ============================================================
  add("pujat", "bid")
  add("puja mínima", "min bid")
  add("alguien más?", "anyone else?")
  add("a la una", "going once")
  add("a las dos", "going twice")
  add("vendido", "sold")
  add("reserva", "reserve")
  add("reservado", "reserved")
  add("todo looteado", "all looted")
  add("reparto de oro", "gold payout")
  add("mi parte", "my share")
  add("cuánto es?", "how much?")
  add("pasa el loot", "pass loot")
  add("tira dados", "roll")
  add("necesidad", "need")
  add("codicia", "greed")
  add("desencantar", "de")

  -- ============================================================
  -- BLOQUE: GRIMORIO DE CLASES (Habilidades V4.0)
  -- ============================================================
  -- Guerrero
  add("golpe heroico", "heroic strike")
  add("hendir armadura", "sunder armor")
  add("ejecutar", "execute")
  add("grito de batalla", "battle shout")
  add("muro de escudo", "shield wall")
  -- Paladín
  add("destello de luz", "flash of light")
  add("luz sagrada", "holy light")
  add("sentencia", "judgement")
  add("escudo divino", "divine shield")
  add("imposición de manos", "lay on hands")
  -- Cazador
  add("disparo de puntería", "aimed shot")
  add("multidisparo", "multi-shot")
  add("fingir muerte", "feign death")
  add("marca del cazador", "hunter's mark")
  -- Pícaro
  add("porrazo", "sap")
  add("golpe en los riñones", "kidney shot")
  add("evasión", "evasion")
  add("esfumarse", "vanish")
  add("ceguera", "blind")
  -- Sacerdote
  add("sanación superior", "greater heal")
  add("sanación relámpago", "flash heal")
  add("escudo de poder", "power word: shield")
  add("infusión de poder", "power infusion")
  -- Mago
  add("descarga de escarcha", "frostbolt")
  add("bola de fuego", "fireball")
  add("bloque de hielo", "ice block")
  add("polimorfia", "polymorph")
  add("traslación", "blink")
  -- Brujo
  add("descarga de sombras", "shadow bolt")
  add("miedo", "fear")
  add("piedra de salud", "healthstone")
  add("piedra de alma", "soulstone")
  -- Chamán
  add("descarga de relámpagos", "lightning bolt")
  add("cadena de relámpagos", "chain lightning")
  add("ansia de sangre", "bloodlust")
  add("furia del viento", "windfury")
  -- Druida
  add("toque de sanación", "healing touch")
  add("estimular", "innervate")
  add("renacer", "battle res")
  add("rejuvenecimiento", "rejuvenation")

  -- ============================================================
  -- BLOQUE: GEOGRAFÍA TURTLE WOW (Zonas V4.0)
  -- ============================================================
  add("tierras fantasmas", "ghostlands")
  add("isla de gillijim", "gillijim's isle")
  add("isla de lapidis", "lapidis isle")
  add("hiraeth", "hiraeth")
  add("tel'abim", "tel-abim")
  add("sueño esmeralda", "emerald dream")
  add("punto de vuelo", "flight point")
  add("piedra de hogar", "hearthstone")

  -- ============================================================
  -- BLOQUE: ADMINISTRACIÓN Y RAID (Jerga Diamond)
  -- ============================================================
  add("mazmorra", "dungeon")
  add("oficial", "officer")
  add("hermandad", "guild")
  add("maestro de hermandad", "guild master")
  add("armonización", "attunement")
  add("durabilidad", "durability")
  add("comida y agua", "food and water")


  -- LÓGICA DE ORDENAMIENTO (Greedy Matching First)
  table.sort(pfUI.translator_dicts.es_en_keys, function(a,b) return strlen(a) > strlen(b) end)
  table.sort(pfUI.translator_dicts.en_es_keys, function(a,b) return strlen(a) > strlen(b) end)

  if pfUI_config.translator and pfUI_config.translator.debug_mode == "1" then
     DEFAULT_CHAT_FRAME:AddMessage("|cff33ffcc[TR]|r Lexicon V3.1 Inyectado con Éxito.")
  end
end)
